UPDATE products SET downloads = '[{"name":"Technical Datasheet","url":"/downloads/focal-isu-130-tech-sheet.pdf"}]'::jsonb WHERE sku = 'CAL-ISU130';
UPDATE products SET downloads = '[{"name":"Technical Datasheet","url":"/downloads/focal-isu-165-tech-sheet.pdf"}]'::jsonb WHERE sku = 'CAL-ISU165';
UPDATE products SET downloads = '[{"name":"Technical Datasheet","url":"/downloads/focal-isu-200-tech-sheet.pdf"}]'::jsonb WHERE sku = 'CAL-ISU200';
UPDATE products SET downloads = '[{"name":"Technical Datasheet","url":"/downloads/focal-isu-690-tech-sheet.pdf"}]'::jsonb WHERE sku = 'CAL-ISU690';
UPDATE products SET downloads = '[{"name":"Technical Datasheet","url":"/downloads/focal-icu-100-tech-sheet.pdf"}]'::jsonb WHERE sku = 'CAL-ICU100';
UPDATE products SET downloads = '[{"name":"Technical Datasheet","url":"/downloads/focal-icu-130-tech-sheet.pdf"}]'::jsonb WHERE sku = 'CAL-ICU130';
UPDATE products SET downloads = '[{"name":"Technical Datasheet","url":"/downloads/focal-icu-165-tech-sheet.pdf"}]'::jsonb WHERE sku = 'CAL-ICU165';
UPDATE products SET downloads = '[{"name":"Technical Datasheet","url":"/downloads/focal-icu-570-tech-sheet.pdf"}]'::jsonb WHERE sku = 'CAL-ICU570';
UPDATE products SET downloads = '[{"name":"Technical Datasheet","url":"/downloads/focal-icu-690-tech-sheet.pdf"}]'::jsonb WHERE sku = 'CAL-ICU690';
UPDATE products SET downloads = '[{"name":"Technical Datasheet","url":"/downloads/focal-is-bmw-100-tech-sheet.pdf"}]'::jsonb WHERE sku = 'CAL-ISBMW100';
UPDATE products SET downloads = '[{"name":"Technical Datasheet","url":"/downloads/focal-is-bmw-100l-tech-sheet.pdf"}]'::jsonb WHERE sku = 'CAL-ISBMW100L';
UPDATE products SET downloads = '[{"name":"Technical Datasheet","url":"/downloads/focal-ic-bmw-100-tech-sheet.pdf"}]'::jsonb WHERE sku = 'CAL-ICBMW100';
UPDATE products SET downloads = '[{"name":"Technical Datasheet","url":"/downloads/focal-ic-bmw-100l-tech-sheet.pdf"}]'::jsonb WHERE sku = 'CAL-ICBMW100L';
UPDATE products SET downloads = '[{"name":"Technical Datasheet","url":"/downloads/focal-icc-bmw-100-tech-sheet.pdf"}]'::jsonb WHERE sku = 'CAL-ICCBMW100';
UPDATE products SET downloads = '[{"name":"Technical Datasheet","url":"/downloads/focal-isub-bmw-2-tech-sheet.pdf"}]'::jsonb WHERE sku = 'CAL-ISUBBMW2';
UPDATE products SET downloads = '[{"name":"Technical Datasheet","url":"/downloads/focal-isub-bmw-4-tech-sheet.pdf"}]'::jsonb WHERE sku = 'CAL-ISUBBMW4';
UPDATE products SET downloads = '[{"name":"Technical Datasheet","url":"/downloads/focal-is-vw-165-tech-sheet.pdf"}]'::jsonb WHERE sku = 'CAL-IS165VW';
UPDATE products SET downloads = '[{"name":"Technical Datasheet","url":"/downloads/focal-is-vw-155-tech-sheet.pdf"}]'::jsonb WHERE sku = 'CAL-IS155VW';
UPDATE products SET downloads = '[{"name":"Technical Datasheet","url":"/downloads/focal-is-vw-180-tech-sheet.pdf"}]'::jsonb WHERE sku = 'CAL-IS180VW';
UPDATE products SET downloads = '[{"name":"Technical Datasheet","url":"/downloads/focal-ic-vw-165-tech-sheet.pdf"}]'::jsonb WHERE sku = 'CAL-IC165VW';
UPDATE products SET downloads = '[{"name":"Technical Datasheet","url":"/downloads/focal-is-ford-165-tech-sheet.pdf"}]'::jsonb WHERE sku = 'CAL-ISFORD165';
UPDATE products SET downloads = '[{"name":"Technical Datasheet","url":"/downloads/focal-is-ford-690-tech-sheet.pdf"}]'::jsonb WHERE sku = 'CAL-ISFORD690';
UPDATE products SET downloads = '[{"name":"Technical Datasheet","url":"/downloads/focal-ic-ford-165-tech-sheet.pdf"}]'::jsonb WHERE sku = 'CAL-ICFORD165-1';
UPDATE products SET downloads = '[{"name":"Technical Datasheet","url":"/downloads/focal-ic-ford-690-tech-sheet.pdf"}]'::jsonb WHERE sku = 'CAL-ICFORD690';
UPDATE products SET downloads = '[{"name":"Technical Datasheet","url":"/downloads/focal-is-psa-165-tech-sheet.pdf"}]'::jsonb WHERE sku = 'CAL-ISPSA165';
UPDATE products SET downloads = '[{"name":"Technical Datasheet","url":"/downloads/focal-ic-psa-165-tech-sheet.pdf"}]'::jsonb WHERE sku = 'CAL-ICPSA165';
UPDATE products SET downloads = '[{"name":"Technical Datasheet","url":"/downloads/focal-is-ren-130-tech-sheet.pdf"}]'::jsonb WHERE sku = 'CAL-ISREN130';
UPDATE products SET downloads = '[{"name":"Technical Datasheet","url":"/downloads/focal-ic-ren-130-tech-sheet.pdf"}]'::jsonb WHERE sku = 'CAL-ICREN130';
UPDATE products SET downloads = '[{"name":"Technical Datasheet","url":"/downloads/focal-is-rns-165-tech-sheet.pdf"}]'::jsonb WHERE sku = 'CAL-ISRNS165';
UPDATE products SET downloads = '[{"name":"Technical Datasheet","url":"/downloads/focal-ic-rns-165-tech-sheet.pdf"}]'::jsonb WHERE sku = 'CAL-ICRNS165';
UPDATE products SET downloads = '[{"name":"Technical Datasheet","url":"/downloads/focal-is-rni-690-tech-sheet.pdf"}]'::jsonb WHERE sku = 'CAL-ISRNI690';
UPDATE products SET downloads = '[{"name":"Technical Datasheet","url":"/downloads/focal-is-toy-165-tech-sheet.pdf"}]'::jsonb WHERE sku = 'CAL-ISTOY165';
UPDATE products SET downloads = '[{"name":"Technical Datasheet","url":"/downloads/focal-is-toy-690-tech-sheet.pdf"}]'::jsonb WHERE sku = 'CAL-ISTOY690';
UPDATE products SET downloads = '[{"name":"Technical Datasheet","url":"/downloads/focal-ic-toy-165-tech-sheet.pdf"}]'::jsonb WHERE sku = 'CAL-ICTOY165';
UPDATE products SET downloads = '[{"name":"Technical Datasheet","url":"/downloads/focal-is-t3y-100-tech-sheet.pdf"}]'::jsonb WHERE sku = 'CAL-IS T3Y 100';
UPDATE products SET downloads = '[{"name":"Technical Datasheet","url":"/downloads/focal-ic-t3y-100-tech-sheet.pdf"}]'::jsonb WHERE sku = 'CAL-IC T3Y 100';
UPDATE products SET downloads = '[{"name":"Technical Datasheet","url":"/downloads/focal-icc-t3y-100-tech-sheet.pdf"}]'::jsonb WHERE sku = 'CAL-ICC T3Y 100';
UPDATE products SET downloads = '[{"name":"Technical Datasheet","url":"/downloads/focal-iw-t3y-200-tech-sheet.pdf"}]'::jsonb WHERE sku = 'CAL-IW-T3Y-200';
UPDATE products SET downloads = '[{"name":"Technical Datasheet","url":"/downloads/focal-is-mbz-100-tech-sheet.pdf"}]'::jsonb WHERE sku = 'Cal-IS MBZ 100';
UPDATE products SET downloads = '[{"name":"Technical Datasheet","url":"/downloads/focal-ic-mbz-100-tech-sheet.pdf"}]'::jsonb WHERE sku = 'Cal-IC MBZ 100';
UPDATE products SET downloads = '[{"name":"Technical Datasheet","url":"/downloads/focal-icr-mbz-100-tech-sheet.pdf"}]'::jsonb WHERE sku = 'Cal-IC MBZ 100-1';
UPDATE products SET downloads = '[{"name":"Technical Datasheet","url":"/downloads/focal-icc-mbz-100-tech-sheet.pdf"}]'::jsonb WHERE sku = 'Cal-ICC-MBZ 100';
UPDATE products SET downloads = '[{"name":"Technical Datasheet","url":"/downloads/focal-ps-165-fe-tech-sheet.pdf"}]'::jsonb WHERE sku = 'CAL-PS165FE';
UPDATE products SET downloads = '[{"name":"Technical Datasheet","url":"/downloads/focal-ps-165-fse-tech-sheet.pdf"}]'::jsonb WHERE sku = 'CAL-PS165FSE';
UPDATE products SET downloads = '[{"name":"Technical Datasheet","url":"/downloads/focal-ps-165-fxe-tech-sheet.pdf"}]'::jsonb WHERE sku = 'CAL-PS165FXE';
UPDATE products SET downloads = '[{"name":"Technical Datasheet","url":"/downloads/focal-ps-165-f3e-tech-sheet.pdf"}]'::jsonb WHERE sku = 'CAL-PS165F3E';
UPDATE products SET downloads = '[{"name":"Technical Datasheet","url":"/downloads/focal-pc-165-fe-tech-sheet.pdf"}]'::jsonb WHERE sku = 'CAL-PC165FE';
UPDATE products SET downloads = '[{"name":"Technical Datasheet","url":"/downloads/focal-p-20-fe-tech-sheet.pdf"}]'::jsonb WHERE sku = 'CAL-P20FE';
UPDATE products SET downloads = '[{"name":"Technical Datasheet","url":"/downloads/focal-p-20-fse-tech-sheet.pdf"}]'::jsonb WHERE sku = 'CAL-P20FSE';
UPDATE products SET downloads = '[{"name":"Technical Datasheet","url":"/downloads/focal-p-25-fe-tech-sheet.pdf"}]'::jsonb WHERE sku = 'CAL-P25FE';
UPDATE products SET downloads = '[{"name":"Technical Datasheet","url":"/downloads/focal-p-25-fse-tech-sheet.pdf"}]'::jsonb WHERE sku = 'CAL-P25FSE';
UPDATE products SET downloads = '[{"name":"Technical Datasheet","url":"/downloads/focal-pc-130-tech-sheet.pdf"}]'::jsonb WHERE sku = 'CAL-PC130';
UPDATE products SET downloads = '[{"name":"Technical Datasheet","url":"/downloads/focal-pc-165-tech-sheet.pdf"}]'::jsonb WHERE sku = 'CAL-PC165';
