-- Migration: Localize all product images (external URLs -> local WebP)
-- Generated: 2026-02-16T01:55:56.879Z
-- Total products with images: 458
-- All images are now local paths (no external URLs)

UPDATE products SET images = ARRAY['/products/cal-audi/audi-a1-android-1.webp', '/products/cal-audi/audi-a1-android-2.webp', '/products/cal-audi/audi-a1-android-3.webp'] WHERE sku = '13.0A1201FHD';
UPDATE products SET images = ARRAY['/products/cal-audi/audi-a1-android-1.webp', '/products/cal-audi/audi-a1-android-2.webp', '/products/cal-audi/audi-a1-android-3.webp'] WHERE sku = '13.0A1201GFHD';
UPDATE products SET images = ARRAY['/products/cal-audi/audi-a6-android-1.webp', '/products/cal-audi/audi-a6-android-2.webp', '/products/cal-audi/audi-a6-android-3.webp'] WHERE sku = '13.0A1206FHD';
UPDATE products SET images = ARRAY['/products/cal-audi/audi-a3-android-1.webp', '/products/cal-audi/audi-a3-android-2.webp', '/products/cal-audi/audi-a3-android-3.webp'] WHERE sku = '13.0A1213FHD';
UPDATE products SET images = ARRAY['/products/cal-audi/audi-a4-android-1.webp', '/products/cal-audi/audi-a4-android-2.webp', '/products/cal-audi/audi-a4-android-3.webp'] WHERE sku = '13.0A1214FHD';
UPDATE products SET images = ARRAY['/products/cal-audi/audi-a6-android-1.webp', '/products/cal-audi/audi-a6-android-2.webp', '/products/cal-audi/audi-a6-android-3.webp'] WHERE sku = '13.0A1216FHD';
UPDATE products SET images = ARRAY['/products/cal-audi/audi-a4-android-1.webp', '/products/cal-audi/audi-a4-android-2.webp', '/products/cal-audi/audi-a4-android-3.webp'] WHERE sku = '13.0A1224FHD';
UPDATE products SET images = ARRAY['/products/cal-audi/audi-a4-android-1.webp', '/products/cal-audi/audi-a4-android-2.webp', '/products/cal-audi/audi-a4-android-3.webp'] WHERE sku = '13.0A1224GFHD';
UPDATE products SET images = ARRAY['/products/cal-audi/audi-a6-android-1.webp', '/products/cal-audi/audi-a6-android-2.webp', '/products/cal-audi/audi-a6-android-3.webp'] WHERE sku = '13.0A1226DFHD';
UPDATE products SET images = ARRAY['/products/cal-audi/audi-a6-android-1.webp', '/products/cal-audi/audi-a6-android-2.webp', '/products/cal-audi/audi-a6-android-3.webp'] WHERE sku = '13.0A1226FHD';
UPDATE products SET images = ARRAY['/products/cal-audi/audi-a6-android-1.webp', '/products/cal-audi/audi-a6-android-2.webp', '/products/cal-audi/audi-a6-android-3.webp'] WHERE sku = '13.0A1236FHD';
UPDATE products SET images = ARRAY['/products/cal-audi/audi-q7-android-1.webp', '/products/cal-audi/audi-q7-android-2.webp', '/products/cal-audi/audi-q7-android-3.webp', '/products/cal-audi/audi-q7-android-4.webp'] WHERE sku = '13.0A1307FHD';
UPDATE products SET images = ARRAY['/products/cal-audi/audi-q3-android-1.webp', '/products/cal-audi/audi-q3-android-2.webp', '/products/cal-audi/audi-q3-android-3.webp'] WHERE sku = '13.0A1313F';
UPDATE products SET images = ARRAY['/products/cal-audi/audi-q3-android-1.webp', '/products/cal-audi/audi-q3-android-2.webp', '/products/cal-audi/audi-q3-android-3.webp'] WHERE sku = '13.0A1313GFHD';
UPDATE products SET images = ARRAY['/products/cal-audi/audi-q5-android-1.webp', '/products/cal-audi/audi-q5-android-2.webp', '/products/cal-audi/audi-q5-android-3.webp'] WHERE sku = '13.0A1315FHD';
UPDATE products SET images = ARRAY['/products/cal-audi/audi-q7-android-1.webp', '/products/cal-audi/audi-q7-android-2.webp', '/products/cal-audi/audi-q7-android-3.webp', '/products/cal-audi/audi-q7-android-4.webp'] WHERE sku = '13.0A1317FHD';
UPDATE products SET images = ARRAY['/products/cal-audi/audi-q5-android-1.webp', '/products/cal-audi/audi-q5-android-2.webp', '/products/cal-audi/audi-q5-android-3.webp'] WHERE sku = '13.0A1325FHD';
UPDATE products SET images = ARRAY['/products/cal-audi/audi-q5-android-1.webp', '/products/cal-audi/audi-q5-android-2.webp', '/products/cal-audi/audi-q5-android-3.webp'] WHERE sku = '13.0A1325GFHD';
UPDATE products SET images = ARRAY['/products/13-0cx302fhd-1.webp', '/products/13-0cx302fhd-2.webp', '/products/13-0cx302fhd-3.webp'] WHERE sku = '13.0CX302FHD';
UPDATE products SET images = ARRAY['/products/13-0cx303fhd-2.webp'] WHERE sku = '13.0CX303FHD';
UPDATE products SET images = ARRAY['/products/mercedes-glk-klasse-android-130-multimedia-ntg-40.webp'] WHERE sku = '13.0CX308FHD';
UPDATE products SET images = ARRAY['/products/13-0cx309fhd-1.webp', '/products/13-0cx309fhd-2.webp', '/products/13-0cx309fhd-3.webp', '/products/13-0cx309fhd-4.webp', '/products/13-0cx309fhd-5.webp', '/products/13-0cx309fhd-6.webp'] WHERE sku = '13.0CX309FHD';
UPDATE products SET images = ARRAY['/products/13-0cx310fhd-1.webp', '/products/13-0cx310fhd-2.webp'] WHERE sku = '13.0CX310FHD';
UPDATE products SET images = ARRAY['/products/mercedes-mlgl-klasse-android-130-multimedia-ntg45.webp'] WHERE sku = '13.0CX3115FHD';
UPDATE products SET images = ARRAY['/products/13-0cx311fhd-1.webp', '/products/13-0cx311fhd-2.webp'] WHERE sku = '13.0CX311FHD';
UPDATE products SET images = ARRAY['/products/13-0cx312fhd-1.webp', '/products/13-0cx312fhd-2.webp'] WHERE sku = '13.0CX312FHD';
UPDATE products SET images = ARRAY['/products/13-0cx315fhd-1.webp', '/products/13-0cx315fhd-2.webp'] WHERE sku = '13.0CX315FHD';
UPDATE products SET images = ARRAY['/products/13-0cx317fhd-1.webp'] WHERE sku = '13.0CX317FHD';
UPDATE products SET images = ARRAY['/products/13-0cx318fhd-1.webp', '/products/13-0cx318fhd-2.webp'] WHERE sku = '13.0CX318FHD';
UPDATE products SET images = ARRAY['/products/mercedes-b-klasse-android-130-multimedia-ntg-50.webp'] WHERE sku = '13.0CX320FHD';
UPDATE products SET images = ARRAY['/products/13-0cx321fhd-1.webp', '/products/13-0cx321fhd-2.webp', '/products/13-0cx321fhd-3.webp'] WHERE sku = '13.0CX321FHD';
UPDATE products SET images = ARRAY['/products/mercedes-cls-klasse-android-130-multimedia-ntg-45.webp'] WHERE sku = '13.0CX326FHD';
UPDATE products SET images = ARRAY['/products/13-0cx329fhd-1.webp', '/products/13-0cx329fhd-2.webp'] WHERE sku = '13.0CX329FHD';
UPDATE products SET images = ARRAY['/products/mercedes-cls-klasse-android-130-multimedia-ntg-50.webp'] WHERE sku = '13.0CX336FHD';
UPDATE products SET images = ARRAY['/products/mercedes-slslk-klasse-android-130-multimedia-ntg-4547.webp'] WHERE sku = '13.0CX337FHD';
UPDATE products SET images = ARRAY['/products/13-0cx353fhd-1.webp', '/products/13-0cx353fhd-2.webp'] WHERE sku = '13.0CX353FHD';
UPDATE products SET images = ARRAY['/products/mercedes-slslc-klasse-android-130-multimedia-ntg-50.webp'] WHERE sku = '13.0CX357FHD';
UPDATE products SET images = ARRAY['/products/13-0cx383fhd-1.webp', '/products/13-0cx383fhd-2.webp'] WHERE sku = '13.0CX383FHD';
UPDATE products SET images = ARRAY['/products/16917-1.webp'] WHERE sku = '16917';
UPDATE products SET images = ARRAY['/products/al-dba-201f-1.webp', '/products/al-dba-201f-2.webp', '/products/al-dba-201f-3.webp', '/products/al-dba-201f-4.webp', '/products/al-dba-201f-5.webp'] WHERE sku = 'AL-DBA 201F';
UPDATE products SET images = ARRAY['/products/apbmw-k4e-1.webp', '/products/apbmw-k4e-2.webp'] WHERE sku = 'APBMW K4E';
UPDATE products SET images = ARRAY['/products/apbmw-k4m-1.webp', '/products/apbmw-k4m-2.webp'] WHERE sku = 'APBMW K4M';
UPDATE products SET images = ARRAY['/products/apbmw-s8-2-1.webp', '/products/apbmw-s8-2-2.webp', '/products/apbmw-s8-2-3.webp'] WHERE sku = 'APBMW S8-2';
UPDATE products SET images = ARRAY['/products/apbmw-x4e-1.webp', '/products/apbmw-x4e-2.webp'] WHERE sku = 'APBMW X4E';
UPDATE products SET images = ARRAY['/products/apbmw-x4m-1.webp', '/products/apbmw-x4m-2.webp'] WHERE sku = 'APBMW X4M';
UPDATE products SET images = ARRAY['/products/apbx-10-as2-1.webp', '/products/apbx-10-as2-4.webp'] WHERE sku = 'APBX 10 AS2';
UPDATE products SET images = ARRAY['/products/apbx-10-ds-1.webp'] WHERE sku = 'APBX 10 DS';
UPDATE products SET images = ARRAY['/products/apbx-10-s4s-1.webp'] WHERE sku = 'APBX 10 S4S';
UPDATE products SET images = ARRAY['/products/apbx-8-as2-1.webp'] WHERE sku = 'APBX 8 AS2';
UPDATE products SET images = ARRAY['/products/apbx-8-ds-1.webp'] WHERE sku = 'APBX 8 DS';
UPDATE products SET images = ARRAY['/products/apbx-8-r-1.webp'] WHERE sku = 'APBX 8 R';
UPDATE products SET images = ARRAY['/products/apk-130-1.webp', '/products/apk-130-2.webp', '/products/apk-130-3.webp'] WHERE sku = 'APK 130';
UPDATE products SET images = ARRAY['/products/apk-163-1.webp', '/products/apk-163-2.webp'] WHERE sku = 'APK 163';
UPDATE products SET images = ARRAY['/products/apk-165-1.webp', '/products/apk-165-2.webp', '/products/apk-165-3.webp'] WHERE sku = 'APK 165';
UPDATE products SET images = ARRAY['/products/apk-165-2-1.webp', '/products/apk-165-2-2.webp'] WHERE sku = 'APK 165 Ω2';
UPDATE products SET images = ARRAY['/products/apk-165p-1.webp', '/products/apk-165p-2.webp', '/products/apk-165p-3.webp', '/products/apk-165p-4.webp', '/products/apk-165p-5.webp'] WHERE sku = 'APK 165P';
UPDATE products SET images = ARRAY['/products/apk-570-1.webp'] WHERE sku = 'APK 570';
UPDATE products SET images = ARRAY['/products/apk-690-1.webp', '/products/apk-690-2.webp'] WHERE sku = 'APK 690';
UPDATE products SET images = ARRAY['/products/aps-10-d-3.webp'] WHERE sku = 'APS 10 D';
UPDATE products SET images = ARRAY['/products/aps-10-s4s-1.webp'] WHERE sku = 'APS 10 S4S';
UPDATE products SET images = ARRAY['/products/aps-8-d-3.webp'] WHERE sku = 'APS 8 D';
UPDATE products SET images = ARRAY['/products/aps-8-r-1.webp'] WHERE sku = 'APS 8 R';
UPDATE products SET images = ARRAY['/products/apx-5-1.webp', '/products/apx-5-2.webp', '/products/apx-5-3.webp', '/products/apx-5-4.webp'] WHERE sku = 'APX 5';
UPDATE products SET images = ARRAY['/products/apx-570-1.webp', '/products/apx-570-2.webp', '/products/apx-570-3.webp', '/products/apx-570-4.webp'] WHERE sku = 'APX 570';
UPDATE products SET images = ARRAY['/products/apx-6-5-1.webp', '/products/apx-6-5-2.webp', '/products/apx-6-5-3.webp', '/products/apx-6-5-4.webp', '/products/apx-6-5-5.webp'] WHERE sku = 'APX 6.5';
UPDATE products SET images = ARRAY['/products/apx-690-1.webp', '/products/apx-690-2.webp', '/products/apx-690-3.webp', '/products/apx-690-4.webp', '/products/apx-690-5.webp'] WHERE sku = 'APX 690';
UPDATE products SET images = ARRAY['/products/pioneer-avic.webp'] WHERE sku = 'AVIC-Z1000-DAB-C';
UPDATE products SET images = ARRAY['/products/pioneer-avic-1.webp'] WHERE sku = 'AVIC-Z830DABC';
UPDATE products SET images = ARRAY['/products/avk6apii-1.webp', '/products/avk6apii-2.webp', '/products/avk6apii-3.webp', '/products/avk6apii-4.webp'] WHERE sku = 'AVK6APII';
UPDATE products SET images = ARRAY['/products/alpine-hce.webp'] WHERE sku = 'Alpine HCE-C1100';
UPDATE products SET images = ARRAY['/products/alpine-spc.webp'] WHERE sku = 'Alpine SPC-200AU-kit';
UPDATE products SET images = ARRAY['/products/audison-af-c4d-1.webp', '/products/audison-af-c4d-2.webp'] WHERE sku = 'Audison AF-C4D-4CH';
UPDATE products SET images = ARRAY['/products/audison-av-1-1-ii-1.webp', '/products/audison-av-1-1-ii-2.webp', '/products/audison-av-1-1-ii-3.webp', '/products/audison-av-1-1-ii-4.webp'] WHERE sku = 'Audison AV 1.1 II';
UPDATE products SET images = ARRAY['/products/audison-av-13-0-ii-speakerset-1.webp', '/products/audison-av-13-0-ii-speakerset-2.webp', '/products/audison-av-13-0-ii-speakerset-3.webp', '/products/audison-av-13-0-ii-speakerset-4.webp'] WHERE sku = 'Audison AV 13.0 II speakerset';
UPDATE products SET images = ARRAY['/products/audison-av-6-5-ii-coaxiaalset-1.webp', '/products/audison-av-6-5-ii-coaxiaalset-2.webp', '/products/audison-av-6-5-ii-coaxiaalset-3.webp', '/products/audison-av-6-5-ii-coaxiaalset-4.webp'] WHERE sku = 'Audison AV 6.5 II coaxiaalset';
UPDATE products SET images = ARRAY['/products/audison-av-6-5-p-ii-woofer-set-1.webp', '/products/audison-av-6-5-p-ii-woofer-set-2.webp', '/products/audison-av-6-5-p-ii-woofer-set-3.webp', '/products/audison-av-6-5-p-ii-woofer-set-4.webp'] WHERE sku = 'Audison AV 6.5 P II woofer-set';
UPDATE products SET images = ARRAY['/products/audison-avk-6-s-ii-coaxiaal-1.webp', '/products/audison-avk-6-s-ii-coaxiaal-2.webp', '/products/audison-avk-6-s-ii-coaxiaal-3.webp', '/products/audison-avk-6-s-ii-coaxiaal-4.webp'] WHERE sku = 'Audison AVK 6 S II coaxiaal';
UPDATE products SET images = ARRAY['/products/audison-avk-6a-ii-coaxiaalset-1.webp', '/products/audison-avk-6a-ii-coaxiaalset-2.webp', '/products/audison-avk-6a-ii-coaxiaalset-3.webp', '/products/audison-avk-6a-ii-coaxiaalset-4.webp'] WHERE sku = 'Audison AVK 6A II coaxiaalset';
UPDATE products SET images = ARRAY['/products/audison-af-c410-bit-1.webp', '/products/audison-af-c410-bit-2.webp'] WHERE sku = 'Audison Forza AF C4.10 bit';
UPDATE products SET images = ARRAY['/products/audison-af-c814-bit-1.webp', '/products/audison-af-c814-bit-2.webp', '/products/audison-af-c814-bit-3.webp'] WHERE sku = 'Audison Forza AF C8.14 bit';
UPDATE products SET images = ARRAY['/products/audison-af-m17-bit-1.webp', '/products/audison-af-m17-bit-2.webp'] WHERE sku = 'Audison Forza AF M1.7 bit';
UPDATE products SET images = ARRAY['/products/audison-af-m1214-bit-1.webp', '/products/audison-af-m1214-bit-2.webp'] WHERE sku = 'Audison Forza AF M12.14 bit';
UPDATE products SET images = ARRAY['/products/audison-af-m511-bit-1.webp', '/products/audison-af-m511-bit-2.webp'] WHERE sku = 'Audison Forza AF M5.11 bit';
UPDATE products SET images = ARRAY['/products/audison-af-m814-bit-1.webp', '/products/audison-af-m814-bit-2.webp', '/products/audison-af-m814-bit-3.webp'] WHERE sku = 'Audison Forza AF M8.14 bit';
UPDATE products SET images = ARRAY['/products/bv-dr590x-1ch-plus-1.webp', '/products/bv-dr590x-1ch-plus-2.webp'] WHERE sku = 'BV-DR590X-1CH-PLUS';
UPDATE products SET images = ARRAY['/products/bv-dr590x-2ch-3.webp', '/products/bv-dr590x-2ch-4.webp'] WHERE sku = 'BV-DR590X-2CH';
UPDATE products SET images = ARRAY['/products/bv-dr770x-1ch-ii-2.webp'] WHERE sku = 'BV-DR770X-1CH-II';
UPDATE products SET images = ARRAY['/products/bv-dr770x-2ch-1.webp'] WHERE sku = 'BV-DR770X-2CH';
UPDATE products SET images = ARRAY['/products/blackvue-dr900x-plus-1ch-closeup-1767204760316.webp', '/products/blackvue-dr900x-plus-1ch-premium-1767204751534.webp'] WHERE sku = 'BV-DR900X-1CH';
UPDATE products SET images = ARRAY['/products/blackvue-dr900x-plus-2ch-closeup-1767204680264.webp', '/products/blackvue-dr900x-plus-2ch-premium-1767204669949.webp'] WHERE sku = 'BV-DR900X-2CH';
UPDATE products SET images = ARRAY['/products/bv-dr970x-1ch-plus-ii-1.webp'] WHERE sku = 'BV-DR970X-1CH-PLUS-II';
UPDATE products SET images = ARRAY['/products/bv-dr970x-2ch-lte-plus-ii-1.webp'] WHERE sku = 'BV-DR970X-2CH-LTE-PLUS-II';
UPDATE products SET images = ARRAY['/products/bv-dr970x-2ch-plus-ii-1.webp'] WHERE sku = 'BV-DR970X-2CH-PLUS-II';
UPDATE products SET images = ARRAY['/products/bv-elite8-1ch-1.webp'] WHERE sku = 'BV-ELITE8-1CH';
UPDATE products SET images = ARRAY['/products/bv-elite8-2ch-1.webp'] WHERE sku = 'BV-ELITE8-2CH';
UPDATE products SET images = ARRAY['/products/blaupunkt-bremen-sqr-46-dab-2.webp', '/products/blaupunkt-bremen-sqr-46-dab-3.webp', '/products/blaupunkt-bremen-sqr-46-dab-4.webp'] WHERE sku = 'Blaupunkt Bremen SQR 46 DAB';
UPDATE products SET images = ARRAY['/products/cal-dbx-30-3-1.webp', '/products/cal-dbx-30-3-2.webp', '/products/cal-dbx-30-3-3.webp'] WHERE sku = 'CAL DBX 30.3';
UPDATE products SET images = ARRAY['/products/alpine-hcs-t100-camerasysteem.webp'] WHERE sku = 'CAL HCS-T100';
UPDATE products SET images = ARRAY['/products/android-multimedia.webp'] WHERE sku = 'CAL-2819';
UPDATE products SET images = ARRAY['/products/acv-camera-ntsc.webp'] WHERE sku = 'CAL-ACV-771000-6003';
UPDATE products SET images = ARRAY['/products/kentekenplaat-camera.webp'] WHERE sku = 'CAL-ACV-771000-6041';
UPDATE products SET images = ARRAY['/products/cal-acv-771000-6207-1.webp', '/products/cal-acv-771000-6207-2.webp', '/products/cal-acv-771000-6207-3.webp', '/products/cal-acv-771000-6207-4.webp'] WHERE sku = 'CAL-ACV-771000-6207';
UPDATE products SET images = ARRAY['/products/accessories/aux-activator-1.webp', '/products/accessories/aux-activator-2.webp', '/products/accessories/aux-activator-3.webp'] WHERE sku = 'CAL-AUX-T01';
UPDATE products SET images = ARRAY['/products/cal-avh-z9200dab-1.webp', '/products/cal-avh-z9200dab-2.webp', '/products/cal-avh-z9200dab-3.webp'] WHERE sku = 'CAL-AVH-Z9200DAB';
UPDATE products SET images = ARRAY['/products/cal-avic-z630bt-c-1.webp', '/products/cal-avic-z630bt-c-2.webp', '/products/cal-avic-z630bt-c-3.webp', '/products/cal-avic-z630bt-c-4.webp'] WHERE sku = 'CAL-AVIC-Z630BT-C';
UPDATE products SET images = ARRAY['/products/cal-avic-z730dab-c-1.webp', '/products/cal-avic-z730dab-c-2.webp', '/products/cal-avic-z730dab-c-3.webp', '/products/cal-avic-z730dab-c-4.webp'] WHERE sku = 'CAL-AVIC-Z730DAB-C';
UPDATE products SET images = ARRAY['/products/cal-bmw-e60-1.webp', '/products/cal-bmw-e60-2.webp', '/products/cal-bmw-e60-3.webp', '/products/cal-bmw-e60-4.webp', '/products/cal-bmw-e60-5.webp', '/products/cal-bmw-e60-6.webp'] WHERE sku = 'CAL-BMW-E60';
UPDATE products SET images = ARRAY['/products/cal-bmw-e65-1.webp', '/products/cal-bmw-e65-2.webp', '/products/cal-bmw-e65-3.webp', '/products/cal-bmw-e65-4.webp', '/products/cal-bmw-e65-5.webp', '/products/cal-bmw-e65-6.webp'] WHERE sku = 'CAL-BMW-E65';
UPDATE products SET images = ARRAY['/products/cal-bmw-e87-1.webp', '/products/cal-bmw-e87-2.webp', '/products/cal-bmw-e87-3.webp', '/products/cal-bmw-e87-4.webp', '/products/cal-bmw-e87-5.webp', '/products/cal-bmw-e87-6.webp'] WHERE sku = 'CAL-BMW-E87';
UPDATE products SET images = ARRAY['/products/cal-bmw-e90-1.webp', '/products/cal-bmw-e90-2.webp', '/products/cal-bmw-e90-3.webp', '/products/cal-bmw-e90-4.webp', '/products/cal-bmw-e90-5.webp', '/products/cal-bmw-e90-6.webp'] WHERE sku = 'CAL-BMW-E90';
UPDATE products SET images = ARRAY['/products/cal-bmw-f01-1.webp', '/products/cal-bmw-f01-2.webp', '/products/cal-bmw-f01-3.webp', '/products/cal-bmw-f01-4.webp', '/products/cal-bmw-f01-5.webp', '/products/cal-bmw-f01-6.webp'] WHERE sku = 'CAL-BMW-F01';
UPDATE products SET images = ARRAY['/products/cal-bmw-f06-1.webp', '/products/cal-bmw-f06-2.webp', '/products/cal-bmw-f06-3.webp', '/products/cal-bmw-f06-4.webp', '/products/cal-bmw-f06-5.webp', '/products/cal-bmw-f06-6.webp'] WHERE sku = 'CAL-BMW-F06';
UPDATE products SET images = ARRAY['/products/cal-bmw-f07-1.webp', '/products/cal-bmw-f07-2.webp', '/products/cal-bmw-f07-3.webp', '/products/cal-bmw-f07-4.webp', '/products/cal-bmw-f07-5.webp', '/products/cal-bmw-f07-6.webp'] WHERE sku = 'CAL-BMW-F07';
UPDATE products SET images = ARRAY['/products/cal-bmw-f10-1.webp', '/products/cal-bmw-f10-2.webp', '/products/cal-bmw-f10-3.webp', '/products/cal-bmw-f10-4.webp', '/products/cal-bmw-f10-5.webp', '/products/cal-bmw-f10-6.webp'] WHERE sku = 'CAL-BMW-F10';
UPDATE products SET images = ARRAY['/products/cal-bmw-f20-1.webp', '/products/cal-bmw-f20-2.webp'] WHERE sku = 'CAL-BMW-F20';
UPDATE products SET images = ARRAY['/products/cal-bmw-f22-1.webp', '/products/cal-bmw-f22-2.webp', '/products/cal-bmw-f22-3.webp', '/products/cal-bmw-f22-4.webp', '/products/cal-bmw-f22-5.webp'] WHERE sku = 'CAL-BMW-F22';
UPDATE products SET images = ARRAY['/products/cal-bmw-f30-1.webp', '/products/cal-bmw-f30-2.webp', '/products/cal-bmw-f30-3.webp', '/products/cal-bmw-f30-4.webp', '/products/cal-bmw-f30-5.webp', '/products/cal-bmw-f30-6.webp'] WHERE sku = 'CAL-BMW-F30';
UPDATE products SET images = ARRAY['/products/cal-bmw-f30-evo-1.webp', '/products/cal-bmw-f30-evo-2.webp', '/products/cal-bmw-f30-evo-3.webp', '/products/cal-bmw-f30-evo-4.webp', '/products/cal-bmw-f30-evo-5.webp', '/products/cal-bmw-f30-evo-6.webp'] WHERE sku = 'CAL-BMW-F30-EVO';
UPDATE products SET images = ARRAY['/products/cal-bmw-g11-1.webp', '/products/cal-bmw-g11-2.webp', '/products/cal-bmw-g11-3.webp', '/products/cal-bmw-g11-4.webp', '/products/cal-bmw-g11-5.webp', '/products/cal-bmw-g11-6.webp'] WHERE sku = 'CAL-BMW-G11';
UPDATE products SET images = ARRAY['/products/cal-bmw-g30-1.webp', '/products/cal-bmw-g30-2.webp', '/products/cal-bmw-g30-3.webp', '/products/cal-bmw-g30-4.webp', '/products/cal-bmw-g30-5.webp', '/products/cal-bmw-g30-6.webp'] WHERE sku = 'CAL-BMW-G30';
UPDATE products SET images = ARRAY['/products/cal-bmw-x1-1.webp', '/products/cal-bmw-x1-2.webp', '/products/cal-bmw-x1-3.webp', '/products/cal-bmw-x1-4.webp', '/products/cal-bmw-x1-5.webp', '/products/cal-bmw-x1-6.webp'] WHERE sku = 'CAL-BMW-X1';
UPDATE products SET images = ARRAY['/products/cal-bmw-x3-1.webp', '/products/cal-bmw-x3-2.webp', '/products/cal-bmw-x3-3.webp', '/products/cal-bmw-x3-4.webp', '/products/cal-bmw-x3-5.webp', '/products/cal-bmw-x3-6.webp'] WHERE sku = 'CAL-BMW-X3';
UPDATE products SET images = ARRAY['/products/cal-bmw-x5-1.webp', '/products/cal-bmw-x5-2.webp', '/products/cal-bmw-x5-3.webp', '/products/cal-bmw-x5-4.webp', '/products/cal-bmw-x5-5.webp', '/products/cal-bmw-x5-6.webp'] WHERE sku = 'CAL-BMW-X5';
UPDATE products SET images = ARRAY['/products/cal-bmw-z4-1.webp', '/products/cal-bmw-z4-2.webp', '/products/cal-bmw-z4-3.webp', '/products/cal-bmw-z4-4.webp', '/products/cal-bmw-z4-5.webp', '/products/cal-bmw-z4-6.webp'] WHERE sku = 'CAL-BMW-Z4';
UPDATE products SET images = ARRAY['/products/boxmore-blox-essential-k200bmw-s21-3.webp'] WHERE sku = 'CAL-BXEK200BMWS2.1';
UPDATE products SET images = ARRAY['/products/boxmore-blox-essential-k200bmw-s41-3.webp'] WHERE sku = 'CAL-BXEK200BMWS4.1';
UPDATE products SET images = ARRAY['/products/boxmore-k200bmw-s21-pasklare-set.webp'] WHERE sku = 'CAL-BXMK200BMW2.1';
UPDATE products SET images = ARRAY['/products/compleet-boxmore-dempingspakket.webp'] WHERE sku = 'CAL-Boxmore-Dempingspakket';
UPDATE products SET images = ARRAY['/products/3e-remlicht-camera-ford-transit-custom-2016.webp'] WHERE sku = 'CAL-CAM-FORD-BR2';
UPDATE products SET images = ARRAY['/products/3e-remlicht-camera-ford-transit-custom-2012.webp'] WHERE sku = 'CAL-CAM-FORD-BRC';
UPDATE products SET images = ARRAY['/products/cal-cam-hd-q1hd-1.webp'] WHERE sku = 'CAL-CAM-HD-Q1HD';
UPDATE products SET images = ARRAY['/products/universele-hd-inbouw-camera-hd.webp'] WHERE sku = 'CAL-CAM-HD-Q5HD';
UPDATE products SET images = ARRAY['/products/3e-remlicht-camera-mb-vito.webp'] WHERE sku = 'CAL-CAM-MB-VTN';
UPDATE products SET images = ARRAY['/products/3e-remlicht-camera-toyota-citroen-en-peugeot.webp'] WHERE sku = 'CAL-CAM-PSA-BRPRO';
UPDATE products SET images = ARRAY['/products/3e-remlicht-camera-opel-en-renault.webp'] WHERE sku = 'CAL-CAM-REN-TF14';
UPDATE products SET images = ARRAY['/products/carvision-m752.webp'] WHERE sku = 'CAL-CAR-200099';
UPDATE products SET images = ARRAY['/products/cal-cba-250-1.webp', '/products/cal-cba-250-2.webp', '/products/cal-cba-250-3.webp', '/products/cal-cba-250-4.webp'] WHERE sku = 'CAL-CBA 250';
UPDATE products SET images = ARRAY['/products/accessories/cp-05-carplay-dongle-1.webp', '/products/accessories/cp-05-carplay-dongle-2.webp'] WHERE sku = 'CAL-CP-05';
UPDATE products SET images = ARRAY['/products/accessories/carplay-interface-1.webp', '/products/accessories/carplay-interface-2.webp', '/products/accessories/carplay-interface-3.webp'] WHERE sku = 'CAL-CP-CARPLAY';
UPDATE products SET images = ARRAY['/products/carplay-dongle.webp'] WHERE sku = 'CAL-Carplay dongle';
UPDATE products SET images = ARRAY['/products/cal-dba-201-1.webp', '/products/cal-dba-201-2.webp', '/products/cal-dba-201-3.webp', '/products/cal-dba-201-4.webp', '/products/cal-dba-201-5.webp'] WHERE sku = 'CAL-DBA 201';
UPDATE products SET images = ARRAY['/products/cal-dbx-25-3-1.webp', '/products/cal-dbx-25-3-2.webp', '/products/cal-dbx-25-3-3.webp'] WHERE sku = 'CAL-DBX 25.3';
UPDATE products SET images = ARRAY['/products/kenwood-dmx5020bt-camper.webp'] WHERE sku = 'CAL-DMX5020BTCamper';
UPDATE products SET images = ARRAY['/products/cal-dmx5020bts-1.webp'] WHERE sku = 'CAL-DMX5020BTS';
UPDATE products SET images = ARRAY['/products/kenwood-dmx5020dab-camper.webp'] WHERE sku = 'CAL-DMX5020DABCamper';
UPDATE products SET images = ARRAY['/products/cal-dmx5020dabs-1.webp'] WHERE sku = 'CAL-DMX5020DABS';
UPDATE products SET images = ARRAY['/products/cal-dmx7525dabscamper-3.webp'] WHERE sku = 'CAL-DMX7525DABS';
UPDATE products SET images = ARRAY['/products/cal-dmx7525dabscamper-3.webp'] WHERE sku = 'CAL-DMX7525DABSCamper';
UPDATE products SET images = ARRAY['/products/kenwood-dmx7722dab-camper.webp'] WHERE sku = 'CAL-DMX7722DABCamper';
UPDATE products SET images = ARRAY['/products/kenwood-dmx7722dabs-digitale-media-ontvanger.webp'] WHERE sku = 'CAL-DMX7722DABS';
UPDATE products SET images = ARRAY['/products/kenwood-dmx8021dab-camper.webp'] WHERE sku = 'CAL-DMX8021DABCamper';
UPDATE products SET images = ARRAY['/products/kenwood-dmx8021dabs-digitale-media-ontvanger.webp'] WHERE sku = 'CAL-DMX8021DABS';
UPDATE products SET images = ARRAY['/products/kenwood-dmx9720xds-multimediasysteem.webp'] WHERE sku = 'CAL-DMX9720XDS';
UPDATE products SET images = ARRAY['/products/cal-dmx9720xdscamper-1.webp'] WHERE sku = 'CAL-DMX9720XDSCamper';
UPDATE products SET images = ARRAY['/products/cal-dnr992rvs-1.webp'] WHERE sku = 'CAL-DNR992RVS';
UPDATE products SET images = ARRAY['/products/kenwood-dnx5190dabs-av.webp'] WHERE sku = 'CAL-DNX5190DABS';
UPDATE products SET images = ARRAY['/products/kenwood-dnx7190dabs-av.webp'] WHERE sku = 'CAL-DNX7190DABS';
UPDATE products SET images = ARRAY['/products/kenwood-dnx9190dabs-av.webp'] WHERE sku = 'CAL-DNX9190DABS';
UPDATE products SET images = ARRAY['/products/focal/cal-ec165k-1.webp', '/products/focal/cal-ec165k-2.webp', '/products/focal/cal-ec165k-3.webp', '/products/focal/cal-ec165k-4.webp', '/products/focal/cal-ec165k-5.webp'] WHERE sku = 'CAL-EC165K';
UPDATE products SET images = ARRAY['/products/focal/cal-esub25kx-1.webp', '/products/focal/cal-esub25kx-2.webp', '/products/focal/cal-esub25kx-3.webp', '/products/focal/cal-esub25kx-4.webp'] WHERE sku = 'CAL-ESUB25KX';
UPDATE products SET images = ARRAY['/products/focal/cal-esub30kx-1.webp', '/products/focal/cal-esub30kx-2.webp', '/products/focal/cal-esub30kx-3.webp', '/products/focal/cal-esub30kx-4.webp'] WHERE sku = 'CAL-ESUB30KX';
UPDATE products SET images = ARRAY['/products/cal-eu35wm-1.webp'] WHERE sku = 'CAL-EU35WM';
UPDATE products SET images = ARRAY['/products/focal/eu6wm-1.webp', '/products/focal/eu6wm-2.webp', '/products/focal/eu6wm-3.webp', '/products/focal/eu6wm-4.webp', '/products/focal/eu6wm-5.webp', '/products/focal/eu6wm-6.webp'] WHERE sku = 'CAL-EU6WM';
UPDATE products SET images = ARRAY['/products/focal/eu8wm-1.webp', '/products/focal/eu8wm-2.webp', '/products/focal/eu8wm-3.webp', '/products/focal/eu8wm-4.webp', '/products/focal/eu8wm-5.webp', '/products/focal/eu8wm-6.webp'] WHERE sku = 'CAL-EU8WM';
UPDATE products SET images = ARRAY['/products/cal-eusub10wm-1.webp'] WHERE sku = 'CAL-EUSUB10WM';
UPDATE products SET images = ARRAY['/products/accessories/fm-modulator-1.webp'] WHERE sku = 'CAL-FM-BOX';
UPDATE products SET images = ARRAY['/products/focal/cal-fpx1-1000-1.webp', '/products/focal/cal-fpx1-1000-2.webp', '/products/focal/cal-fpx1-1000-3.webp'] WHERE sku = 'CAL-FPX1.1000';
UPDATE products SET images = ARRAY['/products/focal/cal-fpx4-400sq-1.webp', '/products/focal/cal-fpx4-400sq-2.webp', '/products/focal/cal-fpx4-400sq-3.webp', '/products/focal/cal-fpx4-400sq-4.webp', '/products/focal/cal-fpx4-400sq-5.webp', '/products/focal/cal-fpx4-400sq-6.webp', '/products/focal/cal-fpx4-400sq-7.webp'] WHERE sku = 'CAL-FPX4.400SQ';
UPDATE products SET images = ARRAY['/products/focal/cal-fpx4-800-1.webp', '/products/focal/cal-fpx4-800-2.webp', '/products/focal/cal-fpx4-800-3.webp', '/products/focal/cal-fpx4-800-4.webp', '/products/focal/cal-fpx4-800-5.webp'] WHERE sku = 'CAL-FPX4.800';
UPDATE products SET images = ARRAY['/products/focal/cal-fpx5-1200-1.webp', '/products/focal/cal-fpx5-1200-2.webp', '/products/focal/cal-fpx5-1200-3.webp', '/products/focal/cal-fpx5-1200-4.webp', '/products/focal/cal-fpx5-1200-5.webp', '/products/focal/cal-fpx5-1200-6.webp', '/products/focal/cal-fpx5-1200-7.webp'] WHERE sku = 'CAL-FPX5.1200';
UPDATE products SET images = ARRAY['/products/cal-focalp60-1.webp'] WHERE sku = 'CAL-FocalP60';
UPDATE products SET images = ARRAY['/products/gcc-m.webp'] WHERE sku = 'CAL-GCC-M-USE 4.3';
UPDATE products SET images = ARRAY['/products/cal-hce-c1100d-1.webp', '/products/cal-hce-c1100d-2.webp', '/products/cal-hce-c1100d-3.webp'] WHERE sku = 'CAL-HCE-C1100D';
UPDATE products SET images = ARRAY['/products/achteruitrijcamera-hce.webp'] WHERE sku = 'CAL-HCE-C2100RD';
UPDATE products SET images = ARRAY['/products/dashboard-camera-hce.webp'] WHERE sku = 'CAL-HCE-C2600FD';
UPDATE products SET images = ARRAY['/products/focal/cal-ibus2-1-1.webp', '/products/focal/cal-ibus2-1-2.webp', '/products/focal/cal-ibus2-1-3.webp', '/products/focal/cal-ibus2-1-4.webp', '/products/focal/cal-ibus2-1-5.webp', '/products/focal/cal-ibus2-1-6.webp', '/products/focal/cal-ibus2-1-7.webp', '/products/focal/cal-ibus2-1-8.webp', '/products/focal/cal-ibus2-1-9.webp'] WHERE sku = 'CAL-IBUS2.1';
UPDATE products SET images = ARRAY['/products/focal/cal-ic-t3y-100-1.webp', '/products/focal/cal-ic-t3y-100-2.webp', '/products/focal/cal-ic-t3y-100-3.webp', '/products/focal/cal-ic-t3y-100-4.webp', '/products/focal/cal-ic-t3y-100-5.webp', '/products/focal/cal-ic-t3y-100-6.webp', '/products/focal/cal-ic-t3y-100-7.webp', '/products/focal/cal-ic-t3y-100-8.webp'] WHERE sku = 'CAL-IC T3Y 100';
UPDATE products SET images = ARRAY['/products/focal/cal-ic165vw-1.webp', '/products/focal/cal-ic165vw-2.webp', '/products/focal/cal-ic165vw-3.webp', '/products/focal/cal-ic165vw-4.webp', '/products/focal/cal-ic165vw-5.webp', '/products/focal/cal-ic165vw-6.webp', '/products/focal/cal-ic165vw-7.webp', '/products/focal/cal-ic165vw-8.webp', '/products/focal/cal-ic165vw-9.webp', '/products/focal/cal-ic165vw-10.webp'] WHERE sku = 'CAL-IC165VW';
UPDATE products SET images = ARRAY['/products/focal/cal-icbmw100-1.webp', '/products/focal/cal-icbmw100-2.webp', '/products/focal/cal-icbmw100-3.webp', '/products/focal/cal-icbmw100-4.webp', '/products/focal/cal-icbmw100-5.webp', '/products/focal/cal-icbmw100-6.webp', '/products/focal/cal-icbmw100-7.webp', '/products/focal/cal-icbmw100-8.webp', '/products/focal/cal-icbmw100-9.webp', '/products/focal/cal-icbmw100-10.webp'] WHERE sku = 'CAL-ICBMW100';
UPDATE products SET images = ARRAY['/products/focal/cal-icbmw100l-1.webp', '/products/focal/cal-icbmw100l-2.webp', '/products/focal/cal-icbmw100l-3.webp', '/products/focal/cal-icbmw100l-4.webp', '/products/focal/cal-icbmw100l-5.webp', '/products/focal/cal-icbmw100l-6.webp', '/products/focal/cal-icbmw100l-7.webp', '/products/focal/cal-icbmw100l-8.webp', '/products/focal/cal-icbmw100l-9.webp', '/products/focal/cal-icbmw100l-10.webp', '/products/focal/cal-icbmw100l-11.webp'] WHERE sku = 'CAL-ICBMW100L';
UPDATE products SET images = ARRAY['/products/focal/cal-icc-t3y-100-1.webp', '/products/focal/cal-icc-t3y-100-2.webp', '/products/focal/cal-icc-t3y-100-3.webp', '/products/focal/cal-icc-t3y-100-4.webp', '/products/focal/cal-icc-t3y-100-5.webp', '/products/focal/cal-icc-t3y-100-6.webp', '/products/focal/cal-icc-t3y-100-7.webp', '/products/focal/cal-icc-t3y-100-8.webp'] WHERE sku = 'CAL-ICC T3Y 100';
UPDATE products SET images = ARRAY['/products/focal/cal-iccbmw100-1.webp', '/products/focal/cal-iccbmw100-2.webp', '/products/focal/cal-iccbmw100-3.webp', '/products/focal/cal-iccbmw100-4.webp', '/products/focal/cal-iccbmw100-5.webp', '/products/focal/cal-iccbmw100-6.webp', '/products/focal/cal-iccbmw100-7.webp', '/products/focal/cal-iccbmw100-8.webp', '/products/focal/cal-iccbmw100-9.webp', '/products/focal/cal-iccbmw100-10.webp', '/products/focal/cal-iccbmw100-11.webp'] WHERE sku = 'CAL-ICCBMW100';
UPDATE products SET images = ARRAY['/products/focal/cal-icford165-1-1.webp', '/products/focal/cal-icford165-1-2.webp', '/products/focal/cal-icford165-1-3.webp', '/products/focal/cal-icford165-1-4.webp', '/products/focal/cal-icford165-1-5.webp', '/products/focal/cal-icford165-1-6.webp', '/products/focal/cal-icford165-1-7.webp', '/products/focal/cal-icford165-1-8.webp', '/products/focal/cal-icford165-1-9.webp', '/products/focal/cal-icford165-1-10.webp'] WHERE sku = 'CAL-ICFORD165-1';
UPDATE products SET images = ARRAY['/products/focal/cal-icford690-1.webp', '/products/focal/cal-icford690-2.webp', '/products/focal/cal-icford690-3.webp', '/products/focal/cal-icford690-4.webp', '/products/focal/cal-icford690-5.webp', '/products/focal/cal-icford690-6.webp', '/products/focal/cal-icford690-7.webp', '/products/focal/cal-icford690-8.webp', '/products/focal/cal-icford690-9.webp'] WHERE sku = 'CAL-ICFORD690';
UPDATE products SET images = ARRAY['/products/focal/cal-icpsa165-1.webp', '/products/focal/cal-icpsa165-2.webp', '/products/focal/cal-icpsa165-3.webp', '/products/focal/cal-icpsa165-4.webp', '/products/focal/cal-icpsa165-5.webp', '/products/focal/cal-icpsa165-6.webp', '/products/focal/cal-icpsa165-7.webp', '/products/focal/cal-icpsa165-8.webp', '/products/focal/cal-icpsa165-9.webp', '/products/focal/cal-icpsa165-10.webp'] WHERE sku = 'CAL-ICPSA165';
UPDATE products SET images = ARRAY['/products/focal/cal-icren130-1.webp', '/products/cal-icren130-2.webp'] WHERE sku = 'CAL-ICREN130';
UPDATE products SET images = ARRAY['/products/focal/cal-icrns165-1.webp', '/products/focal/cal-icrns165-2.webp', '/products/focal/cal-icrns165-3.webp', '/products/focal/cal-icrns165-4.webp'] WHERE sku = 'CAL-ICRNS165';
UPDATE products SET images = ARRAY['/products/focal/cal-ictoy165-1.webp', '/products/focal/cal-ictoy165-2.webp', '/products/focal/cal-ictoy165-3.webp', '/products/focal/cal-ictoy165-4.webp', '/products/focal/cal-ictoy165-5.webp', '/products/focal/cal-ictoy165-6.webp', '/products/focal/cal-ictoy165-7.webp', '/products/focal/cal-ictoy165-8.webp'] WHERE sku = 'CAL-ICTOY165';
UPDATE products SET images = ARRAY['/products/focal/cal-icu100-1.webp', '/products/focal/cal-icu100-2.webp', '/products/focal/cal-icu100-3.webp', '/products/focal/cal-icu100-4.webp', '/products/focal/cal-icu100-5.webp', '/products/focal/cal-icu100-6.webp', '/products/focal/cal-icu100-7.webp', '/products/focal/cal-icu100-8.webp', '/products/focal/cal-icu100-9.webp', '/products/focal/cal-icu100-10.webp'] WHERE sku = 'CAL-ICU100';
UPDATE products SET images = ARRAY['/products/focal/cal-icu130-1.webp', '/products/focal/cal-icu130-2.webp', '/products/focal/cal-icu130-3.webp', '/products/focal/cal-icu130-4.webp', '/products/focal/cal-icu130-5.webp', '/products/focal/cal-icu130-6.webp', '/products/focal/cal-icu130-7.webp', '/products/focal/cal-icu130-8.webp', '/products/focal/cal-icu130-9.webp', '/products/focal/cal-icu130-10.webp'] WHERE sku = 'CAL-ICU130';
UPDATE products SET images = ARRAY['/products/focal/cal-icu165-1.webp', '/products/focal/cal-icu165-2.webp', '/products/focal/cal-icu165-3.webp', '/products/focal/cal-icu165-4.webp', '/products/focal/cal-icu165-5.webp', '/products/focal/cal-icu165-6.webp', '/products/focal/cal-icu165-7.webp', '/products/focal/cal-icu165-8.webp', '/products/focal/cal-icu165-9.webp', '/products/focal/cal-icu165-10.webp'] WHERE sku = 'CAL-ICU165';
UPDATE products SET images = ARRAY['/products/focal/cal-icu570-1.webp', '/products/focal/cal-icu570-2.webp', '/products/focal/cal-icu570-3.webp', '/products/focal/cal-icu570-4.webp', '/products/focal/cal-icu570-5.webp', '/products/focal/cal-icu570-6.webp', '/products/focal/cal-icu570-7.webp', '/products/focal/cal-icu570-8.webp', '/products/focal/cal-icu570-9.webp', '/products/focal/cal-icu570-10.webp'] WHERE sku = 'CAL-ICU570';
UPDATE products SET images = ARRAY['/products/focal/cal-icu690-1.webp', '/products/focal/cal-icu690-2.webp', '/products/focal/cal-icu690-3.webp', '/products/focal/cal-icu690-4.webp', '/products/focal/cal-icu690-5.webp', '/products/focal/cal-icu690-6.webp', '/products/focal/cal-icu690-7.webp', '/products/focal/cal-icu690-8.webp', '/products/focal/cal-icu690-9.webp', '/products/focal/cal-icu690-10.webp', '/products/focal/cal-icu690-11.webp'] WHERE sku = 'CAL-ICU690';
UPDATE products SET images = ARRAY['/products/accessories/idrive-knop-z4-1.webp', '/products/accessories/idrive-knop-z4-2.webp'] WHERE sku = 'CAL-ID-002';
UPDATE products SET images = ARRAY['/products/cal-ilx-705e46-1.webp', '/products/cal-ilx-705e46-2.webp', '/products/cal-ilx-705e46-3.webp', '/products/cal-ilx-705e46-4.webp'] WHERE sku = 'CAL-ILX-705E46';
UPDATE products SET images = ARRAY['/products/cal-ilx-f115du8-1.webp', '/products/cal-ilx-f115du8-2.webp', '/products/cal-ilx-f115du8-3.webp', '/products/cal-ilx-f115du8-4.webp', '/products/cal-ilx-f115du8-5.webp', '/products/cal-ilx-f115du8-6.webp'] WHERE sku = 'CAL-ILX-F115DU8';
UPDATE products SET images = ARRAY['/products/cal-ilx-f115du8s-1.webp', '/products/cal-ilx-f115du8s-2.webp', '/products/cal-ilx-f115du8s-3.webp', '/products/cal-ilx-f115du8s-4.webp', '/products/cal-ilx-f115du8s-5.webp', '/products/cal-ilx-f115du8s-6.webp', '/products/cal-ilx-f115du8s-7.webp'] WHERE sku = 'CAL-ILX-F115DU8S';
UPDATE products SET images = ARRAY['/products/cal-ilx-f115t6-1.webp', '/products/cal-ilx-f115t6-2.webp', '/products/cal-ilx-f115t6-3.webp', '/products/cal-ilx-f115t6-4.webp', '/products/cal-ilx-f115t6-5.webp', '/products/cal-ilx-f115t6-6.webp', '/products/cal-ilx-f115t6-7.webp'] WHERE sku = 'CAL-ILX-F115T6';
UPDATE products SET images = ARRAY['/products/cal-ilx-f115t61-1.webp', '/products/cal-ilx-f115t61-2.webp', '/products/cal-ilx-f115t61-3.webp', '/products/cal-ilx-f115t61-4.webp', '/products/cal-ilx-f115t61-5.webp'] WHERE sku = 'CAL-ILX-F115T61';
UPDATE products SET images = ARRAY['/products/cal-ilx-f115tra-1.webp', '/products/cal-ilx-f115tra-2.webp', '/products/cal-ilx-f115tra-3.webp', '/products/cal-ilx-f115tra-4.webp', '/products/cal-ilx-f115tra-5.webp', '/products/cal-ilx-f115tra-6.webp'] WHERE sku = 'CAL-ILX-F115TRA';
UPDATE products SET images = ARRAY['/products/cal-ilx-f905du8-1.webp', '/products/cal-ilx-f905du8-2.webp', '/products/cal-ilx-f905du8-3.webp', '/products/cal-ilx-f905du8-4.webp', '/products/cal-ilx-f905du8-5.webp'] WHERE sku = 'CAL-ILX-F905DU8';
UPDATE products SET images = ARRAY['/products/cal-ilx-f905du8s-1.webp', '/products/cal-ilx-f905du8s-2.webp', '/products/cal-ilx-f905du8s-3.webp', '/products/cal-ilx-f905du8s-4.webp', '/products/cal-ilx-f905du8s-5.webp', '/products/cal-ilx-f905du8s-6.webp', '/products/cal-ilx-f905du8s-7.webp'] WHERE sku = 'CAL-ILX-F905DU8S';
UPDATE products SET images = ARRAY['/products/cal-ilx-f905s907-1.webp', '/products/cal-ilx-f905s907-2.webp', '/products/cal-ilx-f905s907-3.webp', '/products/cal-ilx-f905s907-4.webp'] WHERE sku = 'CAL-ILX-F905S907';
UPDATE products SET images = ARRAY['/products/cal-ilx-f905t6-1.webp', '/products/cal-ilx-f905t6-2.webp', '/products/cal-ilx-f905t6-3.webp', '/products/cal-ilx-f905t6-4.webp', '/products/cal-ilx-f905t6-5.webp', '/products/cal-ilx-f905t6-6.webp', '/products/cal-ilx-f905t6-7.webp'] WHERE sku = 'CAL-ILX-F905T6';
UPDATE products SET images = ARRAY['/products/cal-ilx-f905t6-1-1.webp', '/products/cal-ilx-f905t6-1-2.webp', '/products/cal-ilx-f905t6-1-3.webp', '/products/cal-ilx-f905t6-1-4.webp', '/products/cal-ilx-f905t6-1-5.webp', '/products/cal-ilx-f905t6-1-6.webp'] WHERE sku = 'CAL-ILX-F905T6-1';
UPDATE products SET images = ARRAY['/products/cal-ilx-f905tra-1.webp', '/products/cal-ilx-f905tra-2.webp', '/products/cal-ilx-f905tra-3.webp', '/products/cal-ilx-f905tra-4.webp', '/products/cal-ilx-f905tra-5.webp', '/products/cal-ilx-f905tra-6.webp', '/products/cal-ilx-f905tra-7.webp'] WHERE sku = 'CAL-ILX-F905TRA';
UPDATE products SET images = ARRAY['/products/cal-ilx-w690du-1.webp', '/products/cal-ilx-w690du-2.webp', '/products/cal-ilx-w690du-3.webp', '/products/cal-ilx-w690du-4.webp'] WHERE sku = 'CAL-ILX-W690DU';
UPDATE products SET images = ARRAY['/products/cal-impulse-1.webp', '/products/cal-impulse-2.webp', '/products/cal-impulse-3.webp', '/products/cal-impulse-4.webp', '/products/cal-impulse-5.webp', '/products/cal-impulse-6.webp', '/products/cal-impulse-7.webp'] WHERE sku = 'CAL-IMPULSE';
UPDATE products SET images = ARRAY['/products/cal-ine-f904d-1.webp', '/products/cal-ine-f904d-2.webp', '/products/cal-ine-f904d-3.webp', '/products/cal-ine-f904d-4.webp', '/products/cal-ine-f904d-5.webp'] WHERE sku = 'CAL-INE-F904D';
UPDATE products SET images = ARRAY['/products/alpine-ine-1.webp'] WHERE sku = 'CAL-INE-F904D incl. KIT-F9FO-TRA';
UPDATE products SET images = ARRAY['/products/alpine-ine-2.webp'] WHERE sku = 'CAL-INE-F904D incl. KIT-F9MB-S907';
UPDATE products SET images = ARRAY['/products/cal-ine-f904dc-1.webp', '/products/cal-ine-f904dc-2.webp', '/products/cal-ine-f904dc-3.webp', '/products/cal-ine-f904dc-4.webp', '/products/cal-ine-f904dc-5.webp'] WHERE sku = 'CAL-INE-F904DC';
UPDATE products SET images = ARRAY['/products/cal-ine-f904du-1.webp', '/products/cal-ine-f904du-2.webp', '/products/cal-ine-f904du-3.webp', '/products/cal-ine-f904du-4.webp'] WHERE sku = 'CAL-INE-F904DU';
UPDATE products SET images = ARRAY['/products/cal-ine-f904du8s-1.webp', '/products/cal-ine-f904du8s-2.webp', '/products/cal-ine-f904du8s-3.webp', '/products/cal-ine-f904du8s-4.webp', '/products/cal-ine-f904du8s-5.webp', '/products/cal-ine-f904du8s-6.webp', '/products/cal-ine-f904du8s-7.webp'] WHERE sku = 'CAL-INE-F904DU8S';
UPDATE products SET images = ARRAY['/products/cal-ine-f904t6-1-1.webp', '/products/cal-ine-f904t6-1-2.webp', '/products/cal-ine-f904t6-1-3.webp', '/products/cal-ine-f904t6-1-4.webp', '/products/cal-ine-f904t6-1-5.webp'] WHERE sku = 'CAL-INE-F904T6-1';
UPDATE products SET images = ARRAY['/products/cal-ine-f904t61-1.webp', '/products/cal-ine-f904t61-2.webp', '/products/cal-ine-f904t61-3.webp', '/products/cal-ine-f904t61-4.webp', '/products/cal-ine-f904t61-5.webp'] WHERE sku = 'CAL-INE-F904T61';
UPDATE products SET images = ARRAY['/products/cal-ine-f904tra-1.webp', '/products/cal-ine-f904tra-2.webp', '/products/cal-ine-f904tra-3.webp'] WHERE sku = 'CAL-INE-F904TRA';
UPDATE products SET images = ARRAY['/products/alpine-7-inch-toestel-ine.webp'] WHERE sku = 'CAL-INE-W720D incl.KIT-7AR-940';
UPDATE products SET images = ARRAY['/products/cal-ine-w720d-mito-1.webp', '/products/cal-ine-w720d-mito-2.webp', '/products/cal-ine-w720d-mito-3.webp', '/products/cal-ine-w720d-mito-4.webp', '/products/cal-ine-w720d-mito-5.webp', '/products/cal-ine-w720d-mito-6.webp'] WHERE sku = 'CAL-INE-W720D-MITO';
UPDATE products SET images = ARRAY['/products/focal/cal-is-t3y-100-1.webp', '/products/focal/cal-is-t3y-100-2.webp', '/products/focal/cal-is-t3y-100-3.webp', '/products/focal/cal-is-t3y-100-4.webp', '/products/focal/cal-is-t3y-100-5.webp', '/products/focal/cal-is-t3y-100-6.webp', '/products/focal/cal-is-t3y-100-7.webp', '/products/focal/cal-is-t3y-100-8.webp'] WHERE sku = 'CAL-IS T3Y 100';
UPDATE products SET images = ARRAY['/products/focal/cal-is155vw-1.webp', '/products/focal/cal-is155vw-2.webp', '/products/focal/cal-is155vw-3.webp', '/products/focal/cal-is155vw-4.webp', '/products/focal/cal-is155vw-5.webp', '/products/focal/cal-is155vw-6.webp', '/products/focal/cal-is155vw-7.webp', '/products/focal/cal-is155vw-8.webp', '/products/focal/cal-is155vw-9.webp', '/products/focal/cal-is155vw-10.webp', '/products/focal/cal-is155vw-11.webp', '/products/focal/cal-is155vw-12.webp'] WHERE sku = 'CAL-IS155VW';
UPDATE products SET images = ARRAY['/products/focal/cal-is165vw-1.webp', '/products/focal/cal-is165vw-2.webp', '/products/focal/cal-is165vw-3.webp', '/products/focal/cal-is165vw-4.webp', '/products/focal/cal-is165vw-5.webp', '/products/focal/cal-is165vw-6.webp', '/products/focal/cal-is165vw-7.webp', '/products/focal/cal-is165vw-8.webp', '/products/focal/cal-is165vw-9.webp', '/products/focal/cal-is165vw-10.webp', '/products/focal/cal-is165vw-11.webp', '/products/focal/cal-is165vw-12.webp', '/products/focal/cal-is165vw-13.webp'] WHERE sku = 'CAL-IS165VW';
UPDATE products SET images = ARRAY['/products/focal/cal-is180vw-1.webp', '/products/focal/cal-is180vw-2.webp', '/products/focal/cal-is180vw-3.webp', '/products/focal/cal-is180vw-4.webp', '/products/focal/cal-is180vw-5.webp', '/products/focal/cal-is180vw-6.webp', '/products/focal/cal-is180vw-7.webp', '/products/focal/cal-is180vw-8.webp', '/products/focal/cal-is180vw-9.webp', '/products/focal/cal-is180vw-10.webp', '/products/focal/cal-is180vw-11.webp', '/products/focal/cal-is180vw-12.webp'] WHERE sku = 'CAL-IS180VW';
UPDATE products SET images = ARRAY['/products/cal-isbmw100-1.webp', '/products/cal-isbmw100-2.webp', '/products/cal-isbmw100-3.webp', '/products/cal-isbmw100-4.webp', '/products/cal-isbmw100-5.webp', '/products/cal-isbmw100-6.webp', '/products/cal-isbmw100-7.webp'] WHERE sku = 'CAL-ISBMW100';
UPDATE products SET images = ARRAY['/products/focal/cal-isbmw100l-1.webp', '/products/focal/cal-isbmw100l-2.webp', '/products/focal/cal-isbmw100l-3.webp', '/products/focal/cal-isbmw100l-4.webp', '/products/focal/cal-isbmw100l-5.webp', '/products/focal/cal-isbmw100l-6.webp', '/products/focal/cal-isbmw100l-7.webp', '/products/focal/cal-isbmw100l-8.webp', '/products/focal/cal-isbmw100l-9.webp', '/products/focal/cal-isbmw100l-10.webp', '/products/focal/cal-isbmw100l-11.webp', '/products/focal/cal-isbmw100l-12.webp', '/products/focal/cal-isbmw100l-13.webp'] WHERE sku = 'CAL-ISBMW100L';
UPDATE products SET images = ARRAY['/products/focal/cal-isford165-1.webp', '/products/focal/cal-isford165-2.webp', '/products/focal/cal-isford165-3.webp', '/products/focal/cal-isford165-4.webp', '/products/focal/cal-isford165-5.webp', '/products/focal/cal-isford165-6.webp', '/products/focal/cal-isford165-7.webp'] WHERE sku = 'CAL-ISFORD165';
UPDATE products SET images = ARRAY['/products/focal/cal-isford690-1.webp', '/products/focal/cal-isford690-2.webp', '/products/focal/cal-isford690-3.webp', '/products/focal/cal-isford690-4.webp', '/products/focal/cal-isford690-5.webp', '/products/focal/cal-isford690-6.webp', '/products/focal/cal-isford690-7.webp', '/products/focal/cal-isford690-8.webp', '/products/focal/cal-isford690-9.webp', '/products/focal/cal-isford690-10.webp'] WHERE sku = 'CAL-ISFORD690';
UPDATE products SET images = ARRAY['/products/focal/cal-ispsa165-1.webp', '/products/focal/cal-ispsa165-2.webp', '/products/focal/cal-ispsa165-3.webp', '/products/focal/cal-ispsa165-4.webp', '/products/focal/cal-ispsa165-5.webp', '/products/focal/cal-ispsa165-6.webp', '/products/focal/cal-ispsa165-7.webp', '/products/focal/cal-ispsa165-8.webp', '/products/focal/cal-ispsa165-9.webp'] WHERE sku = 'CAL-ISPSA165';
UPDATE products SET images = ARRAY['/products/focal/cal-isren130-1.webp', '/products/focal/cal-isren130-2.webp'] WHERE sku = 'CAL-ISREN130';
UPDATE products SET images = ARRAY['/products/focal/cal-isrni690-1.webp', '/products/focal/cal-isrni690-2.webp', '/products/focal/cal-isrni690-3.webp', '/products/focal/cal-isrni690-4.webp'] WHERE sku = 'CAL-ISRNI690';
UPDATE products SET images = ARRAY['/products/focal/cal-isrns165-1.webp', '/products/focal/cal-isrns165-2.webp', '/products/focal/cal-isrns165-3.webp', '/products/focal/cal-isrns165-4.webp'] WHERE sku = 'CAL-ISRNS165';
UPDATE products SET images = ARRAY['/products/focal/cal-istoy165-1.webp', '/products/focal/cal-istoy165-2.webp', '/products/focal/cal-istoy165-3.webp', '/products/focal/cal-istoy165-4.webp', '/products/focal/cal-istoy165-5.webp', '/products/focal/cal-istoy165-6.webp', '/products/focal/cal-istoy165-7.webp', '/products/focal/cal-istoy165-8.webp'] WHERE sku = 'CAL-ISTOY165';
UPDATE products SET images = ARRAY['/products/focal/cal-istoy690-1.webp', '/products/focal/cal-istoy690-2.webp', '/products/focal/cal-istoy690-3.webp', '/products/focal/cal-istoy690-4.webp', '/products/focal/cal-istoy690-5.webp', '/products/focal/cal-istoy690-6.webp', '/products/focal/cal-istoy690-7.webp'] WHERE sku = 'CAL-ISTOY690';
UPDATE products SET images = ARRAY['/products/focal/cal-isu130-1.webp', '/products/focal/cal-isu130-2.webp', '/products/focal/cal-isu130-3.webp', '/products/focal/cal-isu130-4.webp', '/products/focal/cal-isu130-5.webp', '/products/focal/cal-isu130-6.webp', '/products/focal/cal-isu130-7.webp', '/products/focal/cal-isu130-8.webp', '/products/focal/cal-isu130-9.webp', '/products/focal/cal-isu130-10.webp'] WHERE sku = 'CAL-ISU130';
UPDATE products SET images = ARRAY['/products/focal/cal-isu165-1.webp', '/products/focal/cal-isu165-2.webp', '/products/focal/cal-isu165-3.webp', '/products/focal/cal-isu165-4.webp', '/products/focal/cal-isu165-5.webp', '/products/focal/cal-isu165-6.webp', '/products/focal/cal-isu165-7.webp', '/products/focal/cal-isu165-8.webp', '/products/focal/cal-isu165-9.webp', '/products/focal/cal-isu165-10.webp'] WHERE sku = 'CAL-ISU165';
UPDATE products SET images = ARRAY['/products/focal/cal-isu200-1.webp', '/products/focal/cal-isu200-2.webp', '/products/focal/cal-isu200-3.webp', '/products/focal/cal-isu200-4.webp', '/products/focal/cal-isu200-5.webp', '/products/focal/cal-isu200-6.webp', '/products/focal/cal-isu200-7.webp', '/products/focal/cal-isu200-8.webp', '/products/focal/cal-isu200-9.webp', '/products/focal/cal-isu200-10.webp'] WHERE sku = 'CAL-ISU200';
UPDATE products SET images = ARRAY['/products/focal/cal-isu690-1.webp', '/products/focal/cal-isu690-2.webp', '/products/focal/cal-isu690-3.webp', '/products/focal/cal-isu690-4.webp', '/products/focal/cal-isu690-5.webp', '/products/focal/cal-isu690-6.webp', '/products/focal/cal-isu690-7.webp', '/products/focal/cal-isu690-8.webp', '/products/focal/cal-isu690-9.webp', '/products/focal/cal-isu690-10.webp'] WHERE sku = 'CAL-ISU690';
UPDATE products SET images = ARRAY['/products/cal-isub-mbz-2-1.webp'] WHERE sku = 'CAL-ISUB MBZ-2';
UPDATE products SET images = ARRAY['/products/focal/cal-isubbmw2-1.webp', '/products/focal/cal-isubbmw2-2.webp', '/products/focal/cal-isubbmw2-3.webp', '/products/focal/cal-isubbmw2-4.webp', '/products/focal/cal-isubbmw2-5.webp', '/products/focal/cal-isubbmw2-6.webp', '/products/focal/cal-isubbmw2-7.webp', '/products/focal/cal-isubbmw2-8.webp', '/products/focal/cal-isubbmw2-9.webp', '/products/focal/cal-isubbmw2-10.webp'] WHERE sku = 'CAL-ISUBBMW2';
UPDATE products SET images = ARRAY['/products/cal-isubbmw4-1.webp'] WHERE sku = 'CAL-ISUBBMW4';
UPDATE products SET images = ARRAY['/products/focal/cal-iw-t3y-200-1.webp', '/products/focal/cal-iw-t3y-200-2.webp', '/products/focal/cal-iw-t3y-200-3.webp', '/products/focal/cal-iw-t3y-200-4.webp', '/products/focal/cal-iw-t3y-200-5.webp', '/products/focal/cal-iw-t3y-200-6.webp', '/products/focal/cal-iw-t3y-200-7.webp', '/products/focal/cal-iw-t3y-200-8.webp'] WHERE sku = 'CAL-IW-T3Y-200';
UPDATE products SET images = ARRAY['/products/cal-witson/jaguar-fpace-android-1.webp', '/products/cal-witson/jaguar-fpace-android-2.webp', '/products/cal-witson/jaguar-fpace-android-3.webp'] WHERE sku = 'CAL-JAG-FPACE-1619';
UPDATE products SET images = ARRAY['/products/cal-witson/jaguar-ftype-android-1.webp', '/products/cal-witson/jaguar-ftype-android-2.webp', '/products/cal-witson/jaguar-ftype-android-3.webp'] WHERE sku = 'CAL-JAG-FTYPE-1215';
UPDATE products SET images = ARRAY['/products/cal-witson/jaguar-ftype-android-1.webp', '/products/cal-witson/jaguar-ftype-android-2.webp', '/products/cal-witson/jaguar-ftype-android-3.webp'] WHERE sku = 'CAL-JAG-FTYPE-1618';
UPDATE products SET images = ARRAY['/products/cal-witson/jaguar-xf-android-1.webp', '/products/cal-witson/jaguar-xf-android-2.webp', '/products/cal-witson/jaguar-xf-android-3.webp'] WHERE sku = 'CAL-JAG-XF-1215';
UPDATE products SET images = ARRAY['/products/cal-witson/jaguar-xf-android-1.webp', '/products/cal-witson/jaguar-xf-android-2.webp', '/products/cal-witson/jaguar-xf-android-3.webp'] WHERE sku = 'CAL-JAG-XF-1620';
UPDATE products SET images = ARRAY['/products/cal-witson/jaguar-xj-android-1.webp', '/products/cal-witson/jaguar-xj-android-2.webp', '/products/cal-witson/jaguar-xj-android-3.webp'] WHERE sku = 'CAL-JAG-XJ-1215';
UPDATE products SET images = ARRAY['/products/cal-witson/jaguar-xj-android-1.webp', '/products/cal-witson/jaguar-xj-android-2.webp', '/products/cal-witson/jaguar-xj-android-3.webp'] WHERE sku = 'CAL-JAG-XJ-1617';
UPDATE products SET images = ARRAY['/products/cal-kcx403-1.webp'] WHERE sku = 'CAL-KCX403';
UPDATE products SET images = ARRAY['/products/alpine-kit.webp'] WHERE sku = 'CAL-KIT-R1DUC';
UPDATE products SET images = ARRAY['/products/cal-kit-r1mhu-1.webp', '/products/cal-kit-r1mhu-2.webp', '/products/cal-kit-r1mhu-3.webp'] WHERE sku = 'CAL-KIT-R1MHU';
UPDATE products SET images = ARRAY['/products/cal-witson/defender-android-1.webp', '/products/cal-witson/defender-android-2.webp', '/products/cal-witson/defender-android-3.webp'] WHERE sku = 'CAL-LR-DEF-2024';
UPDATE products SET images = ARRAY['/products/cal-witson/discovery-4-android-1.webp', '/products/cal-witson/discovery-4-android-2.webp', '/products/cal-witson/discovery-4-android-3.webp'] WHERE sku = 'CAL-LR-DISC4-1216';
UPDATE products SET images = ARRAY['/products/cal-witson/discovery-5-android-1.webp', '/products/cal-witson/discovery-5-android-2.webp', '/products/cal-witson/discovery-5-android-3.webp'] WHERE sku = 'CAL-LR-DISC5-1718';
UPDATE products SET images = ARRAY['/products/cal-witson/discovery-5-android-1.webp', '/products/cal-witson/discovery-5-android-2.webp', '/products/cal-witson/discovery-5-android-3.webp'] WHERE sku = 'CAL-LR-DISC5-1920';
UPDATE products SET images = ARRAY['/products/cal-witson/discovery-sport-android-1.webp', '/products/cal-witson/discovery-sport-android-2.webp', '/products/cal-witson/discovery-sport-android-3.webp'] WHERE sku = 'CAL-LR-DSPORT-1417';
UPDATE products SET images = ARRAY['/products/cal-witson/discovery-sport-android-1.webp', '/products/cal-witson/discovery-sport-android-2.webp', '/products/cal-witson/discovery-sport-android-3.webp'] WHERE sku = 'CAL-LR-DSPORT-1618';
UPDATE products SET images = ARRAY['/products/cal-mpbx-250-s2-1.webp'] WHERE sku = 'CAL-MPBX 250 S2';
UPDATE products SET images = ARRAY['/products/cal-mpbx-300-s2-1.webp'] WHERE sku = 'CAL-MPBX 300 S2';
UPDATE products SET images = ARRAY['/products/cal-mvb10233h-1.webp', '/products/cal-mvb10233h-2.webp', '/products/cal-mvb10233h-3.webp', '/products/cal-mvb10233h-4.webp'] WHERE sku = 'CAL-MVB10233H';
UPDATE products SET images = ARRAY['/products/pioneer-pio8023-universele-camera.webp'] WHERE sku = 'CAL-NB-BC9';
UPDATE products SET images = ARRAY['/products/multimedia-q.webp'] WHERE sku = 'CAL-NIQ-PO-PCM1';
UPDATE products SET images = ARRAY['/products/accessories/opt-e65-fiber-box-1.webp', '/products/accessories/opt-e65-fiber-box-2.webp'] WHERE sku = 'CAL-OPT-E65';
UPDATE products SET images = ARRAY['/products/focal/cal-p20fe-1.webp', '/products/focal/cal-p20fe-2.webp', '/products/focal/cal-p20fe-3.webp', '/products/focal/cal-p20fe-4.webp', '/products/focal/cal-p20fe-5.webp', '/products/focal/cal-p20fe-6.webp', '/products/focal/cal-p20fe-7.webp', '/products/focal/cal-p20fe-8.webp'] WHERE sku = 'CAL-P20FE';
UPDATE products SET images = ARRAY['/products/focal/cal-p20fse-1.webp', '/products/focal/cal-p20fse-2.webp', '/products/focal/cal-p20fse-3.webp', '/products/focal/cal-p20fse-4.webp', '/products/focal/cal-p20fse-5.webp', '/products/focal/cal-p20fse-6.webp', '/products/focal/cal-p20fse-7.webp', '/products/focal/cal-p20fse-8.webp'] WHERE sku = 'CAL-P20FSE';
UPDATE products SET images = ARRAY['/products/focal/cal-p25fe-1.webp', '/products/focal/cal-p25fe-2.webp', '/products/focal/cal-p25fe-3.webp', '/products/focal/cal-p25fe-4.webp', '/products/focal/cal-p25fe-5.webp', '/products/focal/cal-p25fe-6.webp', '/products/focal/cal-p25fe-7.webp', '/products/focal/cal-p25fe-8.webp', '/products/focal/cal-p25fe-9.webp'] WHERE sku = 'CAL-P25FE';
UPDATE products SET images = ARRAY['/products/focal/cal-p25fse-1.webp', '/products/focal/cal-p25fse-2.webp', '/products/focal/cal-p25fse-3.webp', '/products/focal/cal-p25fse-4.webp', '/products/focal/cal-p25fse-5.webp', '/products/focal/cal-p25fse-6.webp', '/products/focal/cal-p25fse-7.webp', '/products/focal/cal-p25fse-8.webp', '/products/focal/cal-p25fse-9.webp'] WHERE sku = 'CAL-P25FSE';
UPDATE products SET images = ARRAY['/products/focal/cal-pc130-1.webp', '/products/focal/cal-pc130-2.webp', '/products/focal/cal-pc130-3.webp', '/products/focal/cal-pc130-4.webp'] WHERE sku = 'CAL-PC130';
UPDATE products SET images = ARRAY['/products/focal/cal-pc165-1.webp', '/products/focal/cal-pc165-2.webp', '/products/focal/cal-pc165-3.webp', '/products/focal/cal-pc165-4.webp', '/products/focal/cal-pc165-5.webp'] WHERE sku = 'CAL-PC165';
UPDATE products SET images = ARRAY['/products/focal/cal-pc165fe-1.webp', '/products/focal/cal-pc165fe-2.webp', '/products/focal/cal-pc165fe-3.webp', '/products/focal/cal-pc165fe-4.webp', '/products/focal/cal-pc165fe-5.webp', '/products/focal/cal-pc165fe-6.webp', '/products/focal/cal-pc165fe-7.webp', '/products/focal/cal-pc165fe-8.webp', '/products/focal/cal-pc165fe-9.webp'] WHERE sku = 'CAL-PC165FE';
UPDATE products SET images = ARRAY['/products/focal/cal-ps165f3e-1.webp', '/products/focal/cal-ps165f3e-2.webp', '/products/focal/cal-ps165f3e-3.webp', '/products/focal/cal-ps165f3e-4.webp', '/products/focal/cal-ps165f3e-5.webp', '/products/focal/cal-ps165f3e-6.webp', '/products/focal/cal-ps165f3e-7.webp', '/products/focal/cal-ps165f3e-8.webp', '/products/focal/cal-ps165f3e-9.webp', '/products/focal/cal-ps165f3e-10.webp', '/products/focal/cal-ps165f3e-11.webp', '/products/focal/cal-ps165f3e-12.webp'] WHERE sku = 'CAL-PS165F3E';
UPDATE products SET images = ARRAY['/products/focal/cal-ps165fe-1.webp', '/products/focal/cal-ps165fe-2.webp', '/products/focal/cal-ps165fe-3.webp', '/products/focal/cal-ps165fe-4.webp', '/products/focal/cal-ps165fe-5.webp', '/products/focal/cal-ps165fe-6.webp', '/products/focal/cal-ps165fe-7.webp', '/products/focal/cal-ps165fe-8.webp', '/products/focal/cal-ps165fe-9.webp', '/products/focal/cal-ps165fe-10.webp', '/products/focal/cal-ps165fe-11.webp', '/products/focal/cal-ps165fe-12.webp'] WHERE sku = 'CAL-PS165FE';
UPDATE products SET images = ARRAY['/products/focal/cal-ps165fse-1.webp', '/products/focal/cal-ps165fse-2.webp', '/products/focal/cal-ps165fse-3.webp', '/products/focal/cal-ps165fse-4.webp', '/products/focal/cal-ps165fse-5.webp', '/products/focal/cal-ps165fse-6.webp', '/products/focal/cal-ps165fse-7.webp', '/products/focal/cal-ps165fse-8.webp', '/products/focal/cal-ps165fse-9.webp', '/products/focal/cal-ps165fse-10.webp', '/products/focal/cal-ps165fse-11.webp'] WHERE sku = 'CAL-PS165FSE';
UPDATE products SET images = ARRAY['/products/focal/cal-ps165fxe-1.webp', '/products/focal/cal-ps165fxe-2.webp', '/products/focal/cal-ps165fxe-3.webp', '/products/focal/cal-ps165fxe-4.webp', '/products/focal/cal-ps165fxe-5.webp', '/products/focal/cal-ps165fxe-6.webp', '/products/focal/cal-ps165fxe-7.webp', '/products/focal/cal-ps165fxe-8.webp', '/products/focal/cal-ps165fxe-9.webp', '/products/focal/cal-ps165fxe-10.webp'] WHERE sku = 'CAL-PS165FXE';
UPDATE products SET images = ARRAY['/products/cal-witson/rr-evoque-android-1.webp', '/products/cal-witson/rr-evoque-android-2.webp', '/products/cal-witson/rr-evoque-android-3.webp'] WHERE sku = 'CAL-RR-EVOQUE-1216';
UPDATE products SET images = ARRAY['/products/cal-witson/rr-evoque-android-1.webp', '/products/cal-witson/rr-evoque-android-2.webp', '/products/cal-witson/rr-evoque-android-3.webp'] WHERE sku = 'CAL-RR-EVOQUE-1518';
UPDATE products SET images = ARRAY['/products/cal-witson/rr-sport-android-1.webp', '/products/cal-witson/rr-sport-android-2.webp', '/products/cal-witson/rr-sport-android-3.webp'] WHERE sku = 'CAL-RR-SPORT-1013';
UPDATE products SET images = ARRAY['/products/cal-witson/rr-sport-android-1.webp', '/products/cal-witson/rr-sport-android-2.webp', '/products/cal-witson/rr-sport-android-3.webp'] WHERE sku = 'CAL-RR-SPORT-1316';
UPDATE products SET images = ARRAY['/products/cal-witson/rr-sport-android-1.webp', '/products/cal-witson/rr-sport-android-2.webp', '/products/cal-witson/rr-sport-android-3.webp'] WHERE sku = 'CAL-RR-SPORT-1720';
UPDATE products SET images = ARRAY['/products/cal-witson/rr-vogue-android-1.webp', '/products/cal-witson/rr-vogue-android-2.webp', '/products/cal-witson/rr-vogue-android-3.webp'] WHERE sku = 'CAL-RR-VOGUE-1316';
UPDATE products SET images = ARRAY['/products/cal-witson/rr-vogue-android-1.webp', '/products/cal-witson/rr-vogue-android-2.webp', '/products/cal-witson/rr-vogue-android-3.webp'] WHERE sku = 'CAL-RR-VOGUE-1720';
UPDATE products SET images = ARRAY['/products/fiat-android-navigatie-fiat-peugeot-citron.webp'] WHERE sku = 'CAL-RVT5586';
UPDATE products SET images = ARRAY['/products/citron-android-navigatie-citroen.webp'] WHERE sku = 'CAL-RVT5626';
UPDATE products SET images = ARRAY['/products/toyota-android-navigatie-toyota-10.webp'] WHERE sku = 'CAL-RVT5730';
UPDATE products SET images = ARRAY['/products/fiat-android-navigatie-fiat.webp'] WHERE sku = 'CAL-RVT5740';
UPDATE products SET images = ARRAY['/products/cal-rvt5748-1.webp'] WHERE sku = 'CAL-RVT5748';
UPDATE products SET images = ARRAY['/products/vw-android-navigatie-vw-en-seat.webp'] WHERE sku = 'CAL-RVT5767';
UPDATE products SET images = ARRAY['/products/cal-spc-106cra2-1.webp', '/products/cal-spc-106cra2-2.webp', '/products/cal-spc-106cra2-3.webp', '/products/cal-spc-106cra2-4.webp'] WHERE sku = 'CAL-SPC-106CRA2';
UPDATE products SET images = ARRAY['/products/cal-spc-106s907-1.webp', '/products/cal-spc-106s907-2.webp', '/products/cal-spc-106s907-3.webp', '/products/cal-spc-106s907-4.webp'] WHERE sku = 'CAL-SPC-106S907';
UPDATE products SET images = ARRAY['/products/component-luidsprekersysteem-spc.webp'] WHERE sku = 'CAL-SPC-106TRA7';
UPDATE products SET images = ARRAY['/products/alpine-pasklare-speakerset-spc.webp'] WHERE sku = 'CAL-SPC-R100-DU';
UPDATE products SET images = ARRAY['/products/alpine-universele-speakerset-spc.webp'] WHERE sku = 'CAL-SPC-R100S';
UPDATE products SET images = ARRAY['/products/cal-sph-da77dab-2.webp', '/products/cal-sph-da77dab-3.webp', '/products/cal-sph-da77dab-4.webp'] WHERE sku = 'CAL-SPH-DA77DAB';
UPDATE products SET images = ARRAY['/products/cal-sph-evo-107dab-c-d8-1.webp', '/products/cal-sph-evo-107dab-c-d8-2.webp', '/products/cal-sph-evo-107dab-c-d8-3.webp', '/products/cal-sph-evo-107dab-c-d8-4.webp'] WHERE sku = 'CAL-SPH-EVO-107DAB-C-D8';
UPDATE products SET images = ARRAY['/products/cal-sph-evo-107dab-c-s-1.webp', '/products/cal-sph-evo-107dab-c-s-2.webp', '/products/cal-sph-evo-107dab-c-s-3.webp', '/products/cal-sph-evo-107dab-c-s-4.webp'] WHERE sku = 'CAL-SPH-EVO-107DAB-C-S';
UPDATE products SET images = ARRAY['/products/cal-sph-evo-107dab-crm-1.webp', '/products/cal-sph-evo-107dab-crm-2.webp', '/products/cal-sph-evo-107dab-crm-3.webp', '/products/cal-sph-evo-107dab-crm-4.webp'] WHERE sku = 'CAL-SPH-EVO-107DAB-CRM';
UPDATE products SET images = ARRAY['/products/cal-sph-evo-107dab-c-d8-1.webp', '/products/cal-sph-evo-107dab-c-d8-2.webp', '/products/cal-sph-evo-107dab-c-d8-3.webp', '/products/cal-sph-evo-107dab-c-d8-4.webp'] WHERE sku = 'CAL-SPH-EVO-107DAB-D8';
UPDATE products SET images = ARRAY['/products/cal-sph-evo-107dab-crm-1.webp', '/products/cal-sph-evo-107dab-crm-2.webp', '/products/cal-sph-evo-107dab-crm-3.webp', '/products/cal-sph-evo-107dab-crm-4.webp'] WHERE sku = 'CAL-SPH-EVO-107DAB-RM';
UPDATE products SET images = ARRAY['/products/cal-sph-evo-107dab-c-s-1.webp', '/products/cal-sph-evo-107dab-c-s-2.webp', '/products/cal-sph-evo-107dab-c-s-3.webp', '/products/cal-sph-evo-107dab-c-s-4.webp'] WHERE sku = 'CAL-SPH-EVO-107DAB-S';
UPDATE products SET images = ARRAY['/products/cal-sph-evo-107dab-t61-1.webp', '/products/cal-sph-evo-107dab-t61-2.webp', '/products/cal-sph-evo-107dab-t61-3.webp', '/products/cal-sph-evo-107dab-t61-4.webp'] WHERE sku = 'CAL-SPH-EVO-107DAB-T';
UPDATE products SET images = ARRAY['/products/cal-sph-evo-107dab-t61-1.webp', '/products/cal-sph-evo-107dab-t61-2.webp', '/products/cal-sph-evo-107dab-t61-3.webp', '/products/cal-sph-evo-107dab-t61-4.webp'] WHERE sku = 'CAL-SPH-EVO-107DAB-T61';
UPDATE products SET images = ARRAY['/products/cal-sph-evo-107dab-uni-1.webp', '/products/cal-sph-evo-107dab-uni-2.webp', '/products/cal-sph-evo-107dab-uni-3.webp', '/products/cal-sph-evo-107dab-uni-4.webp'] WHERE sku = 'CAL-SPH-EVO-107DAB-UNI';
UPDATE products SET images = ARRAY['/products/cal-sph-evo-107dab-uni2-1.webp', '/products/cal-sph-evo-107dab-uni2-2.webp', '/products/cal-sph-evo-107dab-uni2-3.webp', '/products/cal-sph-evo-107dab-uni2-4.webp'] WHERE sku = 'CAL-SPH-EVO-107DAB-UNI2';
UPDATE products SET images = ARRAY['/products/cal-sph-evo-98dan-c-d7-1.webp', '/products/cal-sph-evo-98dan-c-d7-2.webp', '/products/cal-sph-evo-98dan-c-d7-3.webp', '/products/cal-sph-evo-98dan-c-d7-4.webp'] WHERE sku = 'CAL-SPH-EVO-98DAN-C-D7';
UPDATE products SET images = ARRAY['/products/cal-sph-evo-98dan-c-d8-1.webp', '/products/cal-sph-evo-98dan-c-d8-2.webp', '/products/cal-sph-evo-98dan-c-d8-3.webp', '/products/cal-sph-evo-98dan-c-d8-4.webp'] WHERE sku = 'CAL-SPH-EVO-98DAN-C-D8';
UPDATE products SET images = ARRAY['/products/cal-sph-evo-98dan-c-t-1.webp', '/products/cal-sph-evo-98dan-c-t-2.webp', '/products/cal-sph-evo-98dan-c-t-3.webp', '/products/cal-sph-evo-98dan-c-t-4.webp'] WHERE sku = 'CAL-SPH-EVO-98DAN-C-T';
UPDATE products SET images = ARRAY['/products/cal-sph-evo-98dan-cuni-1.webp', '/products/cal-sph-evo-98dan-cuni-2.webp', '/products/cal-sph-evo-98dan-cuni-3.webp'] WHERE sku = 'CAL-SPH-EVO-98DAN-CUNI';
UPDATE products SET images = ARRAY['/products/cal-sph-evo-98dan-cuni2-1.webp', '/products/cal-sph-evo-98dan-cuni2-2.webp', '/products/cal-sph-evo-98dan-cuni2-3.webp', '/products/cal-sph-evo-98dan-cuni2-4.webp'] WHERE sku = 'CAL-SPH-EVO-98DAN-CUNI2';
UPDATE products SET images = ARRAY['/products/cal-sph-evo-98dan-cvag-1.webp', '/products/cal-sph-evo-98dan-cvag-2.webp', '/products/cal-sph-evo-98dan-cvag-3.webp', '/products/cal-sph-evo-98dan-cvag-4.webp'] WHERE sku = 'CAL-SPH-EVO-98DAN-CVAG';
UPDATE products SET images = ARRAY['/products/cal-sph-evo-98dan-t-1.webp', '/products/cal-sph-evo-98dan-t-2.webp', '/products/cal-sph-evo-98dan-t-3.webp', '/products/cal-sph-evo-98dan-t-4.webp'] WHERE sku = 'CAL-SPH-EVO-98DAN-T';
UPDATE products SET images = ARRAY['/products/cal-sph-evo-98dan-vag-1.webp', '/products/cal-sph-evo-98dan-vag-2.webp', '/products/cal-sph-evo-98dan-vag-3.webp', '/products/cal-sph-evo-98dan-vag-4.webp'] WHERE sku = 'CAL-SPH-EVO-98DAN-VAG';
UPDATE products SET images = ARRAY['/products/cal-sph-evo64dab-2.webp', '/products/cal-sph-evo64dab-3.webp', '/products/cal-sph-evo64dab-4.webp'] WHERE sku = 'CAL-SPH-EVO64DAB';
UPDATE products SET images = ARRAY['/products/cal-sph-evo64dab-clio-1.webp', '/products/cal-sph-evo64dab-clio-2.webp', '/products/cal-sph-evo64dab-clio-3.webp', '/products/cal-sph-evo64dab-clio-4.webp'] WHERE sku = 'CAL-SPH-EVO64DAB-CLIO';
UPDATE products SET images = ARRAY['/products/cal-sph-evo64dab-smab-1.webp', '/products/cal-sph-evo64dab-smab-2.webp', '/products/cal-sph-evo64dab-smab-3.webp'] WHERE sku = 'CAL-SPH-EVO64DAB-SMAB';
UPDATE products SET images = ARRAY['/products/cal-sph-evo64dab-smaw-1.webp', '/products/cal-sph-evo64dab-smaw-2.webp', '/products/cal-sph-evo64dab-smaw-3.webp'] WHERE sku = 'CAL-SPH-EVO64DAB-SMAW';
UPDATE products SET images = ARRAY['/products/pioneer.webp'] WHERE sku = 'CAL-SPH-EVO82DAB-UNI';
UPDATE products SET images = ARRAY['/products/cal-sph-evo950dab-1.webp', '/products/cal-sph-evo950dab-2.webp', '/products/cal-sph-evo950dab-3.webp', '/products/cal-sph-evo950dab-4.webp'] WHERE sku = 'CAL-SPH-EVO950DAB';
UPDATE products SET images = ARRAY['/products/alpine-pasklare-versterker-swa.webp'] WHERE sku = 'CAL-SWA-150KIT';
UPDATE products SET images = ARRAY['/products/alpine-pasklare-subwoofer-swc.webp'] WHERE sku = 'CAL-SWC-D84S';
UPDATE products SET images = ARRAY['/products/alpine-subwoofer-swc.webp'] WHERE sku = 'CAL-SWC-W84TRA7';
UPDATE products SET images = ARRAY['/products/toyota-android-navigatie-toyota-4.webp'] WHERE sku = 'CAL-V5512';
UPDATE products SET images = ARRAY['/products/mercedes-android-navigatie-mercedes.webp'] WHERE sku = 'CAL-V5513';
UPDATE products SET images = ARRAY['/products/mercedes-android-navigatie-mercedes-benz.webp'] WHERE sku = 'CAL-V5517';
UPDATE products SET images = ARRAY['/products/skoda-android-navigatie-skoda.webp'] WHERE sku = 'CAL-V5520';
UPDATE products SET images = ARRAY['/products/renault-android-navigatie-renault.webp'] WHERE sku = 'CAL-V5522';
UPDATE products SET images = ARRAY['/products/seat-android-navigatie-seat.webp'] WHERE sku = 'CAL-V5524';
UPDATE products SET images = ARRAY['/products/audi-android-navigatie-audi.webp'] WHERE sku = 'CAL-V5525';
UPDATE products SET images = ARRAY['/products/toyota-android-navigatie-toyota-5.webp'] WHERE sku = 'CAL-V5534';
UPDATE products SET images = ARRAY['/products/nissan-android-navigatie-nissan.webp'] WHERE sku = 'CAL-V5537';
UPDATE products SET images = ARRAY['/products/cal-v5538-1.webp'] WHERE sku = 'CAL-V5538';
UPDATE products SET images = ARRAY['/products/porsche-android-navigatie-porsche.webp'] WHERE sku = 'CAL-V5546';
UPDATE products SET images = ARRAY['/products/cal-v5556-1.webp'] WHERE sku = 'CAL-V5556';
UPDATE products SET images = ARRAY['/products/mitsubishi-android-navigatie-mitsubishi.webp'] WHERE sku = 'CAL-V5557';
UPDATE products SET images = ARRAY['/products/toyota-android-navigatie-toyota-8.webp'] WHERE sku = 'CAL-V5585';
UPDATE products SET images = ARRAY['/products/toyota-android-navigatie-toyota-9.webp'] WHERE sku = 'CAL-V5587';
UPDATE products SET images = ARRAY['/products/jeep-android-navigatie-jeep-chrysler-dodge.webp'] WHERE sku = 'CAL-V5620C/J';
UPDATE products SET images = ARRAY['/products/peugeot-android-navigatie-peugeot.webp'] WHERE sku = 'CAL-V5637';
UPDATE products SET images = ARRAY['/products/cal-v5709b-1.webp'] WHERE sku = 'CAL-V5709B';
UPDATE products SET images = ARRAY['/products/toyota-android-navigatie-toyota-2.webp'] WHERE sku = 'CAL-V5715';
UPDATE products SET images = ARRAY['/products/peugeot-android-navigatie-peugeotcitron.webp'] WHERE sku = 'CAL-V5738';
UPDATE products SET images = ARRAY['/products/honda-android-navigatie-honda.webp'] WHERE sku = 'CAL-V5756';
UPDATE products SET images = ARRAY['/products/cal-v5766-1.webp'] WHERE sku = 'CAL-V5766';
UPDATE products SET images = ARRAY['/products/cal-v5769-1.webp'] WHERE sku = 'CAL-V5769';
UPDATE products SET images = ARRAY['/products/toyota-android-navigatie-toyota-7.webp'] WHERE sku = 'CAL-V5781';
UPDATE products SET images = ARRAY['/products/suzuki-android-navigatie-suzuki.webp'] WHERE sku = 'CAL-V5796';
UPDATE products SET images = ARRAY['/products/cal-x903d-du-1.webp', '/products/cal-x903d-du-2.webp', '/products/cal-x903d-du-3.webp'] WHERE sku = 'CAL-X903D-DU';
UPDATE products SET images = ARRAY['/products/cal-x903d-du2-1.webp', '/products/cal-x903d-du2-2.webp', '/products/cal-x903d-du2-3.webp', '/products/cal-x903d-du2-4.webp'] WHERE sku = 'CAL-X903D-DU2';
UPDATE products SET images = ARRAY['/products/cal-x903d-du8-1.webp', '/products/cal-x903d-du8-2.webp', '/products/cal-x903d-du8-3.webp', '/products/cal-x903d-du8-4.webp', '/products/cal-x903d-du8-5.webp', '/products/cal-x903d-du8-6.webp', '/products/cal-x903d-du8-7.webp', '/products/cal-x903d-du8-8.webp'] WHERE sku = 'CAL-X903D-DU8';
UPDATE products SET images = ARRAY['/products/cal-x903d-du8s-1.webp', '/products/cal-x903d-du8s-2.webp', '/products/cal-x903d-du8s-3.webp', '/products/cal-x903d-du8s-4.webp', '/products/cal-x903d-du8s-5.webp', '/products/cal-x903d-du8s-6.webp'] WHERE sku = 'CAL-X903D-DU8S';
UPDATE products SET images = ARRAY['/products/cal-ilx-f115s907-1.webp', '/products/cal-ilx-f115s907-2.webp', '/products/cal-ilx-f115s907-3.webp', '/products/cal-ilx-f115s907-4.webp'] WHERE sku = 'CAL-iLX-F115S907';
UPDATE products SET images = ARRAY['/products/alpine-ilx-1.webp'] WHERE sku = 'CAL-iLX705DM';
UPDATE products SET images = ARRAY['/products/cal2852a-1.webp'] WHERE sku = 'CAL2852A';
UPDATE products SET images = ARRAY['/products/cal2852b-1.webp'] WHERE sku = 'CAL2852B';
UPDATE products SET images = ARRAY['/products/android-multimedia-mitsubishi-outlander-2-met-big-screen.webp'] WHERE sku = 'CAL2852C';
UPDATE products SET images = ARRAY['/products/fiat-android-navigatie.webp'] WHERE sku = 'CALHV5202';
UPDATE products SET images = ARRAY['/products/calhv5308-1.webp'] WHERE sku = 'CALHV5308';
UPDATE products SET images = ARRAY['/products/kia-android-navigatie-kia.webp'] WHERE sku = 'CALHV5353';
UPDATE products SET images = ARRAY['/products/hyundai-android-navigatie-hyundai.webp'] WHERE sku = 'CALHV5399';
UPDATE products SET images = ARRAY['/products/calhv5754-1.webp'] WHERE sku = 'CALHV5754';
UPDATE products SET images = ARRAY['/products/ford-android-navigatie.webp'] WHERE sku = 'CALHV5757';
UPDATE products SET images = ARRAY['/products/audi-android-navigatie.webp'] WHERE sku = 'CALHV5763';
UPDATE products SET images = ARRAY['/products/3e-remlicht-camera-fiat-citroen-en-peugeot.webp'] WHERE sku = 'CAM-FIAT-DC';
UPDATE products SET images = ARRAY['/products/3e-remlicht-camera-iveco-daily.webp'] WHERE sku = 'CAM-IVEC-DL15';
UPDATE products SET images = ARRAY['/products/ck-130-1.webp'] WHERE sku = 'CK 130';
UPDATE products SET images = ARRAY['/products/ck-165-1.webp', '/products/ck-165-2.webp', '/products/ck-165-3.webp'] WHERE sku = 'CK 165';
UPDATE products SET images = ARRAY['/products/ck-165-l-1.webp', '/products/ck-165-l-2.webp', '/products/ck-165-l-3.webp'] WHERE sku = 'CK 165 L';
UPDATE products SET images = ARRAY['/products/cpk-165-1.webp', '/products/cpk-165-3.webp'] WHERE sku = 'CPK 165';
UPDATE products SET images = ARRAY['/products/cpk-690-1.webp', '/products/cpk-690-2.webp', '/products/cpk-690-3.webp'] WHERE sku = 'CPK 690';
UPDATE products SET images = ARRAY['/products/cpx-165-3.webp'] WHERE sku = 'CPX 165';
UPDATE products SET images = ARRAY['/products/cpx-690-1.webp', '/products/cpx-690-2.webp'] WHERE sku = 'CPX 690';
UPDATE products SET images = ARRAY['/products/cs-250-s2-1.webp', '/products/cs-250-s2-2.webp', '/products/cs-250-s2-3.webp', '/products/cs-250-s2-4.webp'] WHERE sku = 'CS 250 S2';
UPDATE products SET images = ARRAY['/products/cs-250-s4-1.webp', '/products/cs-250-s4-2.webp', '/products/cs-250-s4-3.webp', '/products/cs-250-s4-4.webp'] WHERE sku = 'CS 250 S4';
UPDATE products SET images = ARRAY['/products/cs-300-s2-1.webp', '/products/cs-300-s2-2.webp', '/products/cs-300-s2-3.webp', '/products/cs-300-s2-4.webp'] WHERE sku = 'CS 300 S2';
UPDATE products SET images = ARRAY['/products/cs-300-s4-1.webp', '/products/cs-300-s4-2.webp', '/products/cs-300-s4-3.webp', '/products/cs-300-s4-4.webp'] WHERE sku = 'CS 300 S4';
UPDATE products SET images = ARRAY['/products/cx-100-1.webp', '/products/cx-100-2.webp', '/products/cx-100-3.webp'] WHERE sku = 'CX 100';
UPDATE products SET images = ARRAY['/products/cx-130-1.webp', '/products/cx-130-2.webp'] WHERE sku = 'CX 130';
UPDATE products SET images = ARRAY['/products/cx-165-1.webp', '/products/cx-165-2.webp', '/products/cx-165-3.webp'] WHERE sku = 'CX 165';
UPDATE products SET images = ARRAY['/products/cx-570-1.webp', '/products/cx-570-2.webp', '/products/cx-570-3.webp'] WHERE sku = 'CX 570';
UPDATE products SET images = ARRAY['/products/cx-690-1.webp', '/products/cx-690-2.webp', '/products/cx-690-3.webp'] WHERE sku = 'CX 690';
UPDATE products SET images = ARRAY['/products/boxmore-k200bmw-s41-pasklare-set.webp'] WHERE sku = 'Cal-BXMK200BMWS4.1';
UPDATE products SET images = ARRAY['/products/focal/cal-ic-mbz-100-1.webp', '/products/focal/cal-ic-mbz-100-2.webp', '/products/focal/cal-ic-mbz-100-3.webp', '/products/focal/cal-ic-mbz-100-4.webp', '/products/focal/cal-ic-mbz-100-5.webp', '/products/focal/cal-ic-mbz-100-6.webp', '/products/focal/cal-ic-mbz-100-7.webp', '/products/focal/cal-ic-mbz-100-8.webp', '/products/focal/cal-ic-mbz-100-9.webp', '/products/focal/cal-ic-mbz-100-10.webp', '/products/focal/cal-ic-mbz-100-11.webp', '/products/focal/cal-ic-mbz-100-12.webp'] WHERE sku = 'Cal-IC MBZ 100';
UPDATE products SET images = ARRAY['/products/focal/cal-ic-mbz-100-1-1.webp', '/products/focal/cal-ic-mbz-100-1-2.webp', '/products/focal/cal-ic-mbz-100-1-3.webp', '/products/focal/cal-ic-mbz-100-1-4.webp', '/products/focal/cal-ic-mbz-100-1-5.webp', '/products/focal/cal-ic-mbz-100-1-6.webp', '/products/focal/cal-ic-mbz-100-1-7.webp', '/products/focal/cal-ic-mbz-100-1-8.webp', '/products/focal/cal-ic-mbz-100-1-9.webp', '/products/focal/cal-ic-mbz-100-1-10.webp'] WHERE sku = 'Cal-IC MBZ 100-1';
UPDATE products SET images = ARRAY['/products/focal/cal-icc-mbz-100-1.webp', '/products/focal/cal-icc-mbz-100-2.webp', '/products/focal/cal-icc-mbz-100-3.webp', '/products/focal/cal-icc-mbz-100-4.webp', '/products/focal/cal-icc-mbz-100-5.webp', '/products/focal/cal-icc-mbz-100-6.webp', '/products/focal/cal-icc-mbz-100-7.webp', '/products/focal/cal-icc-mbz-100-8.webp', '/products/focal/cal-icc-mbz-100-9.webp', '/products/focal/cal-icc-mbz-100-10.webp', '/products/focal/cal-icc-mbz-100-11.webp'] WHERE sku = 'Cal-ICC-MBZ 100';
UPDATE products SET images = ARRAY['/products/focal/cal-is-mbz-100-1.webp', '/products/focal/cal-is-mbz-100-2.webp', '/products/focal/cal-is-mbz-100-3.webp'] WHERE sku = 'Cal-IS MBZ 100';
UPDATE products SET images = ARRAY['/products/dcx-100-3-1.webp', '/products/dcx-100-3-2.webp', '/products/dcx-100-3-3.webp'] WHERE sku = 'DCX 100.3';
UPDATE products SET images = ARRAY['/products/dcx-130-3-1.webp', '/products/dcx-130-3-2.webp', '/products/dcx-130-3-3.webp'] WHERE sku = 'DCX 130.3';
UPDATE products SET images = ARRAY['/products/dcx-160-3-1.webp', '/products/dcx-160-3-2.webp'] WHERE sku = 'DCX 160.3';
UPDATE products SET images = ARRAY['/products/dcx-165-3-1.webp', '/products/dcx-165-3-2.webp', '/products/dcx-165-3-3.webp'] WHERE sku = 'DCX 165.3';
UPDATE products SET images = ARRAY['/products/dcx-170-3-1.webp', '/products/dcx-170-3-2.webp', '/products/dcx-170-3-3.webp'] WHERE sku = 'DCX 170.3';
UPDATE products SET images = ARRAY['/products/dcx-460-3-1.webp', '/products/dcx-460-3-2.webp', '/products/dcx-460-3-3.webp'] WHERE sku = 'DCX 460.3';
UPDATE products SET images = ARRAY['/products/dcx-570-3-1.webp', '/products/dcx-570-3-2.webp', '/products/dcx-570-3-3.webp'] WHERE sku = 'DCX 570.3';
UPDATE products SET images = ARRAY['/products/dcx-690-3-1.webp', '/products/dcx-690-3-2.webp', '/products/dcx-690-3-3.webp'] WHERE sku = 'DCX 690.3';
UPDATE products SET images = ARRAY['/products/dcx-710-3-1.webp', '/products/dcx-710-3-2.webp', '/products/dcx-710-3-3.webp'] WHERE sku = 'DCX 710.3';
UPDATE products SET images = ARRAY['/products/dp-1-500-1.webp', '/products/dp-1-500-2.webp'] WHERE sku = 'DP 1.500';
UPDATE products SET images = ARRAY['/products/dp-2-200-1.webp', '/products/dp-2-200-2.webp'] WHERE sku = 'DP 2.200';
UPDATE products SET images = ARRAY['/products/dp-4-300-1.webp', '/products/dp-4-300-2.webp'] WHERE sku = 'DP 4.300';
UPDATE products SET images = ARRAY['/products/dp-4-400-1.webp', '/products/dp-4-400-2.webp'] WHERE sku = 'DP 4.400';
UPDATE products SET images = ARRAY['/products/dpower-1-1.webp'] WHERE sku = 'DPower 1';
UPDATE products SET images = ARRAY['/products/dsk-130-3-1.webp'] WHERE sku = 'DSK 130.3';
UPDATE products SET images = ARRAY['/products/dsk-160-3-1.webp'] WHERE sku = 'DSK 160.3';
UPDATE products SET images = ARRAY['/products/dsk-165-3-1.webp'] WHERE sku = 'DSK 165.3';
UPDATE products SET images = ARRAY['/products/dsk-170-3-1.webp'] WHERE sku = 'DSK 170.3';
UPDATE products SET images = ARRAY['/products/hcp-5md-1.webp', '/products/hcp-5md-2.webp'] WHERE sku = 'HCP 5MD';
UPDATE products SET images = ARRAY['/products/hmx-6-5ld-c-1.webp', '/products/hmx-6-5ld-c-2.webp'] WHERE sku = 'HMX 6.5LD/C';
UPDATE products SET images = ARRAY['/products/hmx-8-ld-c-1.webp', '/products/hmx-8-ld-c-2.webp'] WHERE sku = 'HMX 8 LD/C';
UPDATE products SET images = ARRAY['/products/ma-kc-013-1.webp'] WHERE sku = 'MA-KC-013';
UPDATE products SET images = ARRAY['/products/3e-remlicht-camera-mb-sprinter-en-vw-crafter.webp'] WHERE sku = 'MA-KC-SPRINTER';
UPDATE products SET images = ARRAY['/products/universele-inbouw-camera.webp'] WHERE sku = 'MA-KC403-50';
UPDATE products SET images = ARRAY['/products/ml-2000-3-1.webp', '/products/ml-2000-3-2.webp', '/products/ml-2000-3-3.webp', '/products/ml-2000-3-4.webp', '/products/ml-2000-3-5.webp'] WHERE sku = 'ML 2000.3';
UPDATE products SET images = ARRAY['/products/ml-2500-3-1.webp', '/products/ml-2500-3-2.webp', '/products/ml-2500-3-3.webp', '/products/ml-2500-3-4.webp', '/products/ml-2500-3-5.webp'] WHERE sku = 'ML 2500.3';
UPDATE products SET images = ARRAY['/products/ml-power-1-1.webp'] WHERE sku = 'ML Power 1';
UPDATE products SET images = ARRAY['/products/ml-power-4-1.webp'] WHERE sku = 'ML Power 4';
UPDATE products SET images = ARRAY['/products/ml-power-5-1.webp'] WHERE sku = 'ML Power 5';
UPDATE products SET images = ARRAY['/products/mlk-165-3-1.webp'] WHERE sku = 'MLK 165.3';
UPDATE products SET images = ARRAY['/products/mlk-1650-3-1.webp'] WHERE sku = 'MLK 1650.3';
UPDATE products SET images = ARRAY['/products/mlk-700-3-1.webp'] WHERE sku = 'MLK 700.3';
UPDATE products SET images = ARRAY['/products/mp-250-d2-3-1.webp'] WHERE sku = 'MP 250 D2.3';
UPDATE products SET images = ARRAY['/products/mp-250-d4-3-1.webp'] WHERE sku = 'MP 250 D4.3';
UPDATE products SET images = ARRAY['/products/mp-300-d2-3-1.webp'] WHERE sku = 'MP 300 D2.3';
UPDATE products SET images = ARRAY['/products/mp-300-d4-3-1.webp'] WHERE sku = 'MP 300 D4.3';
UPDATE products SET images = ARRAY['/products/mpk-130-3-1.webp'] WHERE sku = 'MPK 130.3';
UPDATE products SET images = ARRAY['/products/mpk-163-3-1.webp'] WHERE sku = 'MPK 163.3';
UPDATE products SET images = ARRAY['/products/mpk-165-3-1.webp'] WHERE sku = 'MPK 165.3';
UPDATE products SET images = ARRAY['/products/mpk-1650-3-1.webp'] WHERE sku = 'MPK 1650.3';
UPDATE products SET images = ARRAY['/products/mpk-165p-3-2.webp'] WHERE sku = 'MPK 165P.3';
UPDATE products SET images = ARRAY['/products/mpx-165-3-1.webp'] WHERE sku = 'MPX 165.3';
UPDATE products SET images = ARRAY['/products/mpx-690-3-1.webp'] WHERE sku = 'MPX 690.3';
UPDATE products SET images = ARRAY['/products/pioneer-avh.webp'] WHERE sku = 'Pioneer-AVH-Z7200DAB';
UPDATE products SET images = ARRAY['/products/pioneer-sph-1.webp'] WHERE sku = 'SPH-EVO93DAB-FOR';
UPDATE products SET images = ARRAY['/products/sr-1-500-1.webp', '/products/sr-1-500-2.webp'] WHERE sku = 'SR 1.500';
UPDATE products SET images = ARRAY['/products/sr-4-300-1.webp', '/products/sr-4-300-2.webp'] WHERE sku = 'SR 4.300';
UPDATE products SET images = ARRAY['/products/sr-4-500-1.webp', '/products/sr-4-500-2.webp'] WHERE sku = 'SR 4.500';
UPDATE products SET images = ARRAY['/products/sr-5-600-1.webp', '/products/sr-5-600-2.webp'] WHERE sku = 'SR 5.600';
UPDATE products SET images = ARRAY['/products/ss-12-d2-1.webp', '/products/ss-12-d2-3.webp'] WHERE sku = 'SS 12 D2';
UPDATE products SET images = ARRAY['/products/ss-15-d2-1.webp', '/products/ss-15-d2-3.webp'] WHERE sku = 'SS 15 D2';
UPDATE products SET images = ARRAY['/products/pioneer-sxt.webp'] WHERE sku = 'SXT-C10PS';
UPDATE products SET images = ARRAY['/products/stp-accent-10.webp'] WHERE sku = 'StPAccent10';
UPDATE products SET images = ARRAY['/products/stp-aero-alum.webp'] WHERE sku = 'StPAeroAlum';
UPDATE products SET images = ARRAY['/products/stp-biplast-15.webp'] WHERE sku = 'StPBiplast15';
UPDATE products SET images = ARRAY['/products/stp-biplast-25-wave.webp'] WHERE sku = 'StPBiplast25wave';
UPDATE products SET images = ARRAY['/products/stp-black-gold-bulk.webp'] WHERE sku = 'StPBlackGoldBul';
UPDATE products SET images = ARRAY['/products/stpdoorkitsilver-1.webp', '/products/stpdoorkitsilver-2.webp', '/products/stpdoorkitsilver-3.webp', '/products/stpdoorkitsilver-4.webp'] WHERE sku = 'StPDoorkitSilver';
UPDATE products SET images = ARRAY['/products/stp-massa-bassa.webp'] WHERE sku = 'StPMass''aBass''a';
UPDATE products SET images = ARRAY['/products/stp-noise-block-2.webp'] WHERE sku = 'StPNoiseblock2';
UPDATE products SET images = ARRAY['/products/stp-noise-block-3.webp'] WHERE sku = 'StPNoiseblock3';
UPDATE products SET images = ARRAY['/products/stp-roller-30.webp'] WHERE sku = 'StPRoller30';
UPDATE products SET images = ARRAY['/products/stp-roller-40.webp'] WHERE sku = 'StPRoller40';
UPDATE products SET images = ARRAY['/products/stp-roller-profi.webp'] WHERE sku = 'StPRollerProfi';
UPDATE products SET images = ARRAY['/products/stp-splen04.webp'] WHERE sku = 'StSplen04';
UPDATE products SET images = ARRAY['/products/alpine-ute.webp'] WHERE sku = 'UTE-204DAB';
UPDATE products SET images = ARRAY['/products/cal-dme-r1200-1.webp', '/products/cal-dme-r1200-2.webp'] WHERE sku = 'cal-dme-r1200';
UPDATE products SET images = ARRAY['/products/alpine-ilx-w690du8-digitaal-media-systeem.webp'] WHERE sku = 'cal-iLX W690DU8';
UPDATE products SET images = ARRAY['/products/alpine-ine-w611du8.webp'] WHERE sku = 'cal-ine-w611du8';
UPDATE products SET images = ARRAY['/products/pioneer-sph.webp'] WHERE sku = 'cal-sph-da97-dab';
UPDATE products SET images = ARRAY['/products/alpine-x903d.webp'] WHERE sku = 'cal-x903DV447';
UPDATE products SET images = ARRAY['/products/silent-coat-black-volume-pack-2mm-20-sheets.webp'] WHERE sku = 'scbv pack 2mm';
UPDATE products SET images = ARRAY['/products/scbxl-1.webp'] WHERE sku = 'scbxl';
UPDATE products SET images = ARRAY['/products/silent-coat-extra-4mm-volume-pack-12-sheets.webp'] WHERE sku = 'scexvol';
