-- Migration: Replace AI-generated product images with WordPress source images
-- Generated: 2026-02-15T15:38:12.012Z
-- Total products updated: 112
-- AI patterns removed: studio, angle45, topdown, dramatic, lifestyle

BEGIN;

UPDATE products SET images = ARRAY['/products/3e-remlicht-camera-fiat-citroen-en-peugeot-wp.jpg'] WHERE sku = 'CAM-FIAT-DC';
UPDATE products SET images = ARRAY['/products/3e-remlicht-camera-ford-transit-custom-2012-wp.jpg'] WHERE sku = 'CAL-CAM-FORD-BRC';
UPDATE products SET images = ARRAY['/products/3e-remlicht-camera-ford-transit-custom-2016-wp.jpg'] WHERE sku = 'CAL-CAM-FORD-BR2';
UPDATE products SET images = ARRAY['/products/3e-remlicht-camera-iveco-daily-wp.jpg'] WHERE sku = 'CAM-IVEC-DL15';
UPDATE products SET images = ARRAY['/products/3e-remlicht-camera-mb-sprinter-en-vw-crafter-wp.jpg'] WHERE sku = 'MA-KC-SPRINTER';
UPDATE products SET images = ARRAY['/products/3e-remlicht-camera-opel-en-renault-wp.jpg'] WHERE sku = 'CAL-CAM-REN-TF14';
UPDATE products SET images = ARRAY['/products/3e-remlicht-camera-mb-vito-wp.jpg'] WHERE sku = 'CAL-CAM-MB-VTN';
UPDATE products SET images = ARRAY['/products/3e-remlicht-camera-toyota-citroen-en-peugeot-wp.png'] WHERE sku = 'CAL-CAM-PSA-BRPRO';
UPDATE products SET images = ARRAY['/products/acv-camera-ntsc-wp.jpg'] WHERE sku = 'CAL-ACV-771000-6003';
UPDATE products SET images = ARRAY['/products/alpine-ine-2-wp.jpg'] WHERE sku = 'CAL-INE-F904D incl. KIT-F9MB-S907';
UPDATE products SET images = ARRAY['/products/alpine-pasklare-speakerset-spc-wp.jpg'] WHERE sku = 'CAL-SPC-R100-DU';
UPDATE products SET images = ARRAY['/products/alpine-pasklare-subwoofer-swc-wp.jpg'] WHERE sku = 'CAL-SWC-D84S';
UPDATE products SET images = ARRAY['/products/alpine-pasklare-versterker-swa-wp.jpg'] WHERE sku = 'CAL-SWA-150KIT';
UPDATE products SET images = ARRAY['/products/alpine-universele-speakerset-spc-wp.jpeg'] WHERE sku = 'CAL-SPC-R100S';
UPDATE products SET images = ARRAY['/products/achteruitrijcamera-hce-wp.jpg'] WHERE sku = 'CAL-HCE-C2100RD';
UPDATE products SET images = ARRAY['/products/alpine-7-inch-toestel-ine-wp.jpg'] WHERE sku = 'CAL-INE-W720D incl.KIT-7AR-940';
UPDATE products SET images = ARRAY['/products/alpine-hce-wp.jpg'] WHERE sku = 'Alpine HCE-C1100';
UPDATE products SET images = ARRAY['/products/alpine-hcs-t100-camerasysteem-wp.jpg'] WHERE sku = 'CAL HCS-T100';
UPDATE products SET images = ARRAY['/products/alpine-ine-w611du8-wp.jpg'] WHERE sku = 'cal-ine-w611du8';
UPDATE products SET images = ARRAY['/products/alpine-ine-1-wp.jpg'] WHERE sku = 'CAL-INE-F904D incl. KIT-F9FO-TRA';
UPDATE products SET images = ARRAY['/products/alpine-kit-wp.jpg'] WHERE sku = 'CAL-KIT-R1DUC';
UPDATE products SET images = ARRAY['/products/alpine-spc-wp.jpg'] WHERE sku = 'Alpine SPC-200AU-kit';
UPDATE products SET images = ARRAY['/products/alpine-ute-wp.jpg'] WHERE sku = 'UTE-204DAB';
UPDATE products SET images = ARRAY['/products/alpine-x903d-wp.jpg'] WHERE sku = 'cal-x903DV447';
UPDATE products SET images = ARRAY['/products/alpine-ilx-1-wp.jpg'] WHERE sku = 'CAL-iLX705DM';
UPDATE products SET images = ARRAY['/products/alpine-ilx-w690du8-digitaal-media-systeem-wp.jpg'] WHERE sku = 'cal-iLX W690DU8';
UPDATE products SET images = ARRAY['/products/alpine-subwoofer-swc-wp.jpg'] WHERE sku = 'CAL-SWC-W84TRA7';
UPDATE products SET images = ARRAY['/products/android-multimedia-wp.jpg'] WHERE sku = 'CAL-2819';
UPDATE products SET images = ARRAY['/products/android-multimedia-mitsubishi-outlander-2-met-big-screen-wp.jpg'] WHERE sku = 'CAL2852C';
UPDATE products SET images = ARRAY['/products/audi-android-navigatie-wp.jpg'] WHERE sku = 'CALHV5763';
UPDATE products SET images = ARRAY['/products/audi-android-navigatie-audi-wp.jpg'] WHERE sku = 'CAL-V5525';
UPDATE products SET images = ARRAY['/products/boxmore-k200bmw-s41-pasklare-set-wp.jpg'] WHERE sku = 'Cal-BXMK200BMWS4.1';
UPDATE products SET images = ARRAY['/products/boxmore-blox-essential-k200bmw-s21-3-wp.jpg'] WHERE sku = 'CAL-BXEK200BMWS2.1';
UPDATE products SET images = ARRAY['/products/boxmore-blox-essential-k200bmw-s41-3-wp.jpg'] WHERE sku = 'CAL-BXEK200BMWS4.1';
UPDATE products SET images = ARRAY['/products/boxmore-k200bmw-s21-pasklare-set-wp.jpg'] WHERE sku = 'CAL-BXMK200BMW2.1';
UPDATE products SET images = ARRAY['/products/carplay-dongle-wp.png'] WHERE sku = 'CAL-Carplay dongle';
UPDATE products SET images = ARRAY['/products/carvision-m752-wp.jpg'] WHERE sku = 'CAL-CAR-200099';
UPDATE products SET images = ARRAY['/products/citron-android-navigatie-citroen-wp.jpg'] WHERE sku = 'CAL-RVT5626';
UPDATE products SET images = ARRAY['/products/compleet-boxmore-dempingspakket-wp.jpg'] WHERE sku = 'CAL-Boxmore-Dempingspakket';
UPDATE products SET images = ARRAY['/products/component-luidsprekersysteem-spc-wp.jpg'] WHERE sku = 'CAL-SPC-106TRA7';
UPDATE products SET images = ARRAY['/products/dashboard-camera-hce-wp.jpg'] WHERE sku = 'CAL-HCE-C2600FD';
UPDATE products SET images = ARRAY['/products/fiat-android-navigatie-wp.jpeg'] WHERE sku = 'CALHV5202';
UPDATE products SET images = ARRAY['/products/fiat-android-navigatie-fiat-wp.jpeg'] WHERE sku = 'CAL-RVT5740';
UPDATE products SET images = ARRAY['/products/fiat-android-navigatie-fiat-peugeot-citron-wp.jpg'] WHERE sku = 'CAL-RVT5586';
UPDATE products SET images = ARRAY['/products/ford-android-navigatie-wp.jpg'] WHERE sku = 'CALHV5757';
UPDATE products SET images = ARRAY['/products/gcc-m-wp.webp'] WHERE sku = 'CAL-GCC-M-USE 4.3';
UPDATE products SET images = ARRAY['/products/honda-android-navigatie-honda-wp.jpg'] WHERE sku = 'CAL-V5756';
UPDATE products SET images = ARRAY['/products/hyundai-android-navigatie-hyundai-wp.jpg'] WHERE sku = 'CALHV5399';
UPDATE products SET images = ARRAY['/products/jeep-android-navigatie-jeep-chrysler-dodge-wp.jpg'] WHERE sku = 'CAL-V5620C/J';
UPDATE products SET images = ARRAY['/products/kentekenplaat-camera-wp.png'] WHERE sku = 'CAL-ACV-771000-6041';
UPDATE products SET images = ARRAY['/products/kenwood-dmx5020bt-camper-wp.png'] WHERE sku = 'CAL-DMX5020BTCamper';
UPDATE products SET images = ARRAY['/products/kenwood-dmx5020dab-camper-wp.png'] WHERE sku = 'CAL-DMX5020DABCamper';
UPDATE products SET images = ARRAY['/products/kenwood-dmx7722dab-camper-wp.png'] WHERE sku = 'CAL-DMX7722DABCamper';
UPDATE products SET images = ARRAY['/products/kenwood-dmx7722dabs-digitale-media-ontvanger-wp.png'] WHERE sku = 'CAL-DMX7722DABS';
UPDATE products SET images = ARRAY['/products/kenwood-dmx8021dab-camper-wp.png'] WHERE sku = 'CAL-DMX8021DABCamper';
UPDATE products SET images = ARRAY['/products/kenwood-dmx8021dabs-digitale-media-ontvanger-wp.png'] WHERE sku = 'CAL-DMX8021DABS';
UPDATE products SET images = ARRAY['/products/kenwood-dmx9720xds-multimediasysteem-wp.png'] WHERE sku = 'CAL-DMX9720XDS';
UPDATE products SET images = ARRAY['/products/kenwood-dnx5190dabs-av-wp.png'] WHERE sku = 'CAL-DNX5190DABS';
UPDATE products SET images = ARRAY['/products/kenwood-dnx7190dabs-av-wp.png'] WHERE sku = 'CAL-DNX7190DABS';
UPDATE products SET images = ARRAY['/products/kenwood-dnx9190dabs-av-wp.png'] WHERE sku = 'CAL-DNX9190DABS';
UPDATE products SET images = ARRAY['/products/kia-android-navigatie-kia-wp.jpg'] WHERE sku = 'CALHV5353';
UPDATE products SET images = ARRAY['/products/mercedes-android-navigatie-mercedes-wp.jpg'] WHERE sku = 'CAL-V5513';
UPDATE products SET images = ARRAY['/products/mercedes-android-navigatie-mercedes-benz-wp.jpg'] WHERE sku = 'CAL-V5517';
UPDATE products SET images = ARRAY['/products/mercedes-mlgl-klasse-android-130-multimedia-ntg45-wp.jpg'] WHERE sku = '13.0CX3115FHD';
UPDATE products SET images = ARRAY['/products/mercedes-b-klasse-android-130-multimedia-ntg-50-wp.jpg'] WHERE sku = '13.0CX320FHD';
UPDATE products SET images = ARRAY['/products/mercedes-cls-klasse-android-130-multimedia-ntg-45-wp.jpg'] WHERE sku = '13.0CX326FHD';
UPDATE products SET images = ARRAY['/products/mercedes-cls-klasse-android-130-multimedia-ntg-50-wp.jpg'] WHERE sku = '13.0CX336FHD';
UPDATE products SET images = ARRAY['/products/mercedes-glk-klasse-android-130-multimedia-ntg-40-wp.jpg'] WHERE sku = '13.0CX308FHD';
UPDATE products SET images = ARRAY['/products/mercedes-slslc-klasse-android-130-multimedia-ntg-50-wp.jpg'] WHERE sku = '13.0CX357FHD';
UPDATE products SET images = ARRAY['/products/mercedes-slslk-klasse-android-130-multimedia-ntg-4547-wp.jpg'] WHERE sku = '13.0CX337FHD';
UPDATE products SET images = ARRAY['/products/mitsubishi-android-navigatie-mitsubishi-wp.jpg'] WHERE sku = 'CAL-V5557';
UPDATE products SET images = ARRAY['/products/multimedia-q-wp.jpg'] WHERE sku = 'CAL-NIQ-PO-PCM1';
UPDATE products SET images = ARRAY['/products/nissan-android-navigatie-nissan-wp.jpg'] WHERE sku = 'CAL-V5537';
UPDATE products SET images = ARRAY['/products/pioneer-avic-wp.jpg'] WHERE sku = 'AVIC-Z1000-DAB-C';
UPDATE products SET images = ARRAY['/products/pioneer-sph-1-wp.jpg'] WHERE sku = 'SPH-EVO93DAB-FOR';
UPDATE products SET images = ARRAY['/products/pioneer-sxt-wp.jpg'] WHERE sku = 'SXT-C10PS';
UPDATE products SET images = ARRAY['/products/peugeot-android-navigatie-peugeot-wp.jpg'] WHERE sku = 'CAL-V5637';
UPDATE products SET images = ARRAY['/products/peugeot-android-navigatie-peugeotcitron-wp.jpg'] WHERE sku = 'CAL-V5738';
UPDATE products SET images = ARRAY['/products/pioneer-wp.jpg'] WHERE sku = 'CAL-SPH-EVO82DAB-UNI';
UPDATE products SET images = ARRAY['/products/pioneer-avh-wp.jpg'] WHERE sku = 'Pioneer-AVH-Z7200DAB';
UPDATE products SET images = ARRAY['/products/pioneer-avic-1-wp.jpg'] WHERE sku = 'AVIC-Z830DABC';
UPDATE products SET images = ARRAY['/products/pioneer-pio8023-universele-camera-wp.jpg'] WHERE sku = 'CAL-NB-BC9';
UPDATE products SET images = ARRAY['/products/pioneer-sph-wp.jpg'] WHERE sku = 'cal-sph-da97-dab';
UPDATE products SET images = ARRAY['/products/porsche-android-navigatie-porsche-wp.jpg'] WHERE sku = 'CAL-V5546';
UPDATE products SET images = ARRAY['/products/renault-android-navigatie-renault-wp.jpg'] WHERE sku = 'CAL-V5522';
UPDATE products SET images = ARRAY['/products/stp-roller-30-wp.jpg'] WHERE sku = 'StPRoller30';
UPDATE products SET images = ARRAY['/products/stp-roller-40-wp.png'] WHERE sku = 'StPRoller40';
UPDATE products SET images = ARRAY['/products/stp-roller-profi-wp.jpg'] WHERE sku = 'StPRollerProfi';
UPDATE products SET images = ARRAY['/products/seat-android-navigatie-seat-wp.jpg'] WHERE sku = 'CAL-V5524';
UPDATE products SET images = ARRAY['/products/silent-coat-black-volume-pack-2mm-20-sheets-wp.jpg'] WHERE sku = 'scbv pack 2mm';
UPDATE products SET images = ARRAY['/products/silent-coat-extra-4mm-volume-pack-12-sheets-wp.jpg'] WHERE sku = 'scexvol';
UPDATE products SET images = ARRAY['/products/skoda-android-navigatie-skoda-wp.jpg'] WHERE sku = 'CAL-V5520';
UPDATE products SET images = ARRAY['/products/stp-accent-10-wp.jpg'] WHERE sku = 'StPAccent10';
UPDATE products SET images = ARRAY['/products/stp-aero-alum-wp.jpg'] WHERE sku = 'StPAeroAlum';
UPDATE products SET images = ARRAY['/products/stp-biplast-15-wp.jpg'] WHERE sku = 'StPBiplast15';
UPDATE products SET images = ARRAY['/products/stp-biplast-25-wave-wp.jpg'] WHERE sku = 'StPBiplast25wave';
UPDATE products SET images = ARRAY['/products/stp-black-gold-bulk-wp.jpg'] WHERE sku = 'StPBlackGoldBul';
UPDATE products SET images = ARRAY['/products/stp-massa-bassa-wp.jpg'] WHERE sku = 'StPMass''aBass''a';
UPDATE products SET images = ARRAY['/products/stp-noise-block-2-wp.jpg'] WHERE sku = 'StPNoiseblock2';
UPDATE products SET images = ARRAY['/products/stp-noise-block-3-wp.jpg'] WHERE sku = 'StPNoiseblock3';
UPDATE products SET images = ARRAY['/products/stp-splen04-wp.jpg'] WHERE sku = 'StSplen04';
UPDATE products SET images = ARRAY['/products/suzuki-android-navigatie-suzuki-wp.jpg'] WHERE sku = 'CAL-V5796';
UPDATE products SET images = ARRAY['/products/toyota-android-navigatie-toyota-10-wp.jpg'] WHERE sku = 'CAL-RVT5730';
UPDATE products SET images = ARRAY['/products/toyota-android-navigatie-toyota-2-wp.jpg'] WHERE sku = 'CAL-V5715';
UPDATE products SET images = ARRAY['/products/toyota-android-navigatie-toyota-4-wp.jpg'] WHERE sku = 'CAL-V5512';
UPDATE products SET images = ARRAY['/products/toyota-android-navigatie-toyota-5-wp.jpg'] WHERE sku = 'CAL-V5534';
UPDATE products SET images = ARRAY['/products/toyota-android-navigatie-toyota-7-wp.jpg'] WHERE sku = 'CAL-V5781';
UPDATE products SET images = ARRAY['/products/toyota-android-navigatie-toyota-8-wp.jpg'] WHERE sku = 'CAL-V5585';
UPDATE products SET images = ARRAY['/products/toyota-android-navigatie-toyota-9-wp.jpg'] WHERE sku = 'CAL-V5587';
UPDATE products SET images = ARRAY['/products/universele-hd-inbouw-camera-hd-wp.jpeg'] WHERE sku = 'CAL-CAM-HD-Q5HD';
UPDATE products SET images = ARRAY['/products/universele-inbouw-camera-wp.jpg'] WHERE sku = 'MA-KC403-50';
UPDATE products SET images = ARRAY['/products/vw-android-navigatie-vw-en-seat-wp.jpg'] WHERE sku = 'CAL-RVT5767';

-- Unmatched product: clear AI-generated images (no source in CSV)
UPDATE products SET images = ARRAY[]::text[] WHERE sku = 'SPKUP-VWG';

COMMIT;
